### ISSUE TITLE
Server ping is not accurate at all.

### ISSUE THREAD

**Issue by Blackpillar** [ic3w0lf22/Roblox-Account-Manager#10]
I am not sure how the server pinging works in the 'Server List' but I know for sure it's not pinging from my computer. The main reason I am using Roblox Account Manager is to connect to UK servers for low ping because roblox can't do it for the life of it.

**Comment by ic3w0lf22** [comment]
The ping value comes from the roblox api itself, obviously roblox doesn't make the server ips public so you can't just ping it yourself to find it. You can look for yourself [here](https://games.roblox.com/v1/games/5208655184/servers/public?limit=100&cursor=)

**Comment by Blackpillar** [comment]
Thanks for the info, do you know where the pings are coming from tho? So I can at least try and make sense of which servers might suite me best.
