### ISSUE TITLE
[Question] Failed to load back up file

### ISSUE THREAD

**Issue by phoriah** [ic3w0lf22/Roblox-Account-Manager#100]
Recently I shut down my pc and I think the account data files corrupted. It says it can't load account data file then prompts to load back-up which fails too. 
Question: Is there way to repair / recover the back up file to make it work?
Or is there any other place where I can look for history of logins?

I only need to find the Names of accounts as I remember the passwords.
Thanks, P.

**Comment by ic3w0lf22** [comment]
It is not possible to decrypt the file as roblox account manager uses your PC to encrypt the file. This shouldn't happen though so maybe I'll add a different way to have your AccountData encrypted, preferably a password.

**Comment by TheSpiderYT** [comment]
I am having the same problem, here are some of the messages:

![image](https://user-images.githubusercontent.com/93413129/194241826-3c9ab6b0-fdf0-49c0-b0fe-02946e2f9979.png)
![image](https://user-images.githubusercontent.com/93413129/194241887-b33f441a-39fa-4b29-b73d-719dd189e78b.png)

If I try to add the accounts back, it makes the manager close

**Comment by ic3w0lf22** [comment]
You can now disable encryption, scroll to the bottom of the README to find out how.
