### ISSUE TITLE
[Suggestion] Random JobId instead of "Play" behavior

### ISSUE THREAD

**Issue by phoriah** [ic3w0lf22/Roblox-Account-Manager#101]
I think it'd be useful to have toggle which causes auto-relaunch and "join server" to pick random JobId from specified PlaceId instead of using behavior similar to "Play" button Roblox (if I'm understanding how it works correctly).
This would bypass the 524 error.
Example:
If you join some sub-places (which can usually be only accessed through main game in the universe) with just the PlaceId it will kick you and say you are not permitted to join this game/server.
But if you specify any of the JobIds it will work all the time.
Thanks, P.

**Comment by ic3w0lf22** [comment]
Added in next update
