### ISSUE TITLE
BRICKED DUE TO ROBLOX BETA APP

### ISSUE THREAD

**Issue by itsweekly** [ic3w0lf22/Roblox-Account-Manager#104]
dude, i know this is a multi launcher. IT IS BRICKED AS IT DOESNT LAUNCH YOUR ACCOUNT WHEN YOU PRESS LAUNCH. IT LAUNCHES THE BETA ROBLOX APP.

**Comment by itsweekly** [comment]
UPDATE : you can get it to work by setting only run as admin and deleting the beta app aka the virus still when you press leave it shows the stupid beta app

**Comment by ic3w0lf22** [comment]
this is a roblox launcher so according to what you're saying, it is launching roblox just fine :)
