### ISSUE TITLE
launches beta app instead of launcher + fix!

### ISSUE THREAD

**Issue by itsweekly** [ic3w0lf22/Roblox-Account-Manager#105]
hi so i made a issue a few times im not sure you understand me but it does not fully work anymore due to roblox pushing the beta app
recently today they just made it so you cant alt f4 anymore as that will also bring you to the beta app and if you try to remove the actual file from roblox directory it says roblox isnt installed 

fix that you have to do every update:

download modified client exe (not mine)
https://github.com/lolmanurfunny/Roblox-Launcher-minus-the-app/raw/main/RobloxPlayerLauncher.exe
go to your roblox appdata %USERPROFILE%/AppData/Local/Roblox/Versions
replace the playerlauncher with the one you downloaded

this currently works and the current version version-b117c4c276664452

ADD THIS TO THE DESCRIPTION ALOT OF PEOPLE HAVE ISSUES WITH THIS

**Comment by ic3w0lf22** [comment]
this is just a launcher, not a roblox patcher.

don't send random exes under my repo's issues

**Comment by itsweekly** [comment]
i know it is not a roblox patcher just listen to what i wrote

**Comment by itsweekly** [comment]
> this is just a launcher, not a roblox patcher.
> 
> don't send random exes under my repo's issues

bro can you read what i wrote literally the launcher does not work

**Comment by ic3w0lf22** [comment]
if it's launching roblox, it works. you're saying you're able to launch the roblox app just fine which is intended, as all this does is launch roblox as if you clicked play on the website

**Comment by itsweekly** [comment]
> if it's launching roblox, it works. you're saying you're able to launch the roblox app just fine which is intended, as all this does is launch roblox as if you clicked play on the website

bro you cant read what i just said i just said its launching the roblox app then NOT launching any games

**Comment by ic3w0lf22** [comment]
how hard was it to say that? you never mentioned that it doesn't launch into a game...

**Comment by itsweekly** [comment]
> how hard was it to say that? you never mentioned that it doesn't launch into a game...

if yyou can put my original text into the description because this issue isnt only me

**Comment by ic3w0lf22** [comment]
no i'm not putting a random exe that could be malicious into the readme.

**Comment by itsweekly** [comment]
> no i'm not putting a random exe that could be malicious into the readme.

bro what its not mine plus ive literally tested it and if you want your project to be broken go ahead because this is the only working method to get rid of the beta app
