### ISSUE TITLE
the roblox apps automaticly closed after click follow 

### ISSUE THREAD

**Issue by joeycuties** [ic3w0lf22/Roblox-Account-Manager#106]
I have an issue when clicking follow button the Roblox account manager, the Roblox apps game would load the launch menu, then it would close the one that already launched. it only allowed me to launch 1 account only. Last time I can click follow 2 accounts for 2 Roblox account apps. please help.

**Comment by ic3w0lf22** [comment]
read faq

**Comment by joeycuties** [comment]
> I always wanted to have all my roblox account to join the same experience as one that already is in game. I tried adding the account name of the one they should follow but clicking follow does not see to do anything. How are you getting this feature to work ?

first you need to select the Roblox account that you just added, then put the name of the user you want to follow on the follow collum. then click follow.

**Comment by joeycuties** [comment]
> read faq

which faq? I read all but none of them stated about follow bug problem.

**Comment by ic3w0lf22** [comment]
> > read faq
> 
> which faq? I read all but none of them stated about follow bug problem.

oops, this question isnt on the README, but in the discord instead. i'll update the README faq with the next update.

Q: Multi roblox does not work!
A: Close every process of the Roblox client. Open Task Manager, go to the Details tab, scroll down and look for processes named RobloxPlayerBeta.exe, right click and click End Task on all of them. 
After you are done with that, restart Roblox Account Manager.

**Comment by joeycuties** [comment]
> > > read faq
> > 
> > 
> > which faq? I read all but none of them stated about follow bug problem.
> 
> oops, this question isnt on the README, but in the discord instead. i'll update the README faq with the next update.
> 
> Q: Multi roblox does not work! A: Close every process of the Roblox client. Open Task Manager, go to the Details tab, scroll down and look for processes named RobloxPlayerBeta.exe, right click and click End Task on all of them. After you are done with that, restart Roblox Account Manager.

- thank you. actually, that one still does not work. I just try to use process explorer for windows, then I would have to close handle for the singleton event. it works to launch multiple Roblox follow after I close handle the singleton event every time I want to launch another Roblox account.
