### ISSUE TITLE
Auto Relaunch tries to open 2 roblox windows on the same account

### ISSUE THREAD

**Issue by witchoyy** [ic3w0lf22/Roblox-Account-Manager#108]
I use auto relaunch for an autofarm and every time it closes, it relaunches after 1 minute and launches another on the same account 30 seconds - 1 minute later. Any fix?

**Comment by ZackDaQuack** [comment]
Same problem here. One time is crashed my computer since it open so many.

**Comment by ic3w0lf22** [comment]
Not enough details provided, please provide steps to reproduce

Did you install Nexus correctly?
Are the red circles turning green in Account Control?
Are you using a supported executor? (officially Synapse only, Nexus will work if your executor has a proper WebSocket class)
