### ISSUE TITLE
Text scaling messed up after reinstalling RAM

### ISSUE THREAD

**Issue by oTradeMark** [ic3w0lf22/Roblox-Account-Manager#115]
Recently I had an issue with my account data getting corrupted and RAM saying "failed to load back up file" every time I launched it, so I re-downloaded the latest release and now my RAM looks like this:
https://i.imgur.com/BDtPZJv.png

Is there a way that I can fix the text scaling so the program is usable again? I've tried changing windows text scaling and that doesn't help.

**Comment by ic3w0lf22** [comment]
What's your screen resolution and your scale option set at?
Open `RAMSettings.ini` and tell me what your WindowScale setting is at

**Comment by oTradeMark** [comment]
> 
WindowScale=2.0
Resolution is a 4k TV, windows text scaling I've tried everywhere from 100% to 300% and it doesn't change how RAM appears

**Comment by ic3w0lf22** [comment]
I can't reproduce this issue considering I don't have a 4k monitor.
What happens if you change `WindowScale=2.0` to `WindowScale=1.0`

**Comment by ic3w0lf22** [comment]
I've added an option called `ScaleFonts`, run the AutoUpdater, close RAM, open `RAMSettings.ini`, change `ScaleFonts=true` to `ScaleFonts=false`, then restart RAM. LMK if this fixes the issue

**Comment by oTradeMark** [comment]
> I've added an option called `ScaleFonts`, run the AutoUpdater, close RAM, open `RAMSettings.ini`, change `ScaleFonts=true` to `ScaleFonts=false`, then restart RAM. Let me know if this fixes the issue

Works perfectly, thank you so much. I really love Roblox Alt Manager, it's saved me so much time since I discovered it and I have been struggling without it. Fixing my issue really means a lot to me, thanks again.
