### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by Equalis-programming** [ic3w0lf22/Roblox-Account-Manager#120]
Can you create a MacOS version please ? it will be very useful for me and other MacOS users

**Comment by ic3w0lf22** [comment]
[Launchbox](https://github.com/ccrpr/launchbox) has MacOS support but I'm not sure if it is in a working state yet.

**Comment by ic3w0lf22** [comment]
This program isn't MacOS based so I'll be closing this issue now.
