### ISSUE TITLE
the file is blank and it says what to open with something

### ISSUE THREAD

**Issue by bigjayrbk3** [ic3w0lf22/Roblox-Account-Manager#122]
when i try to open it it says this 
![image](https://user-images.githubusercontent.com/117794886/200731550-a0bb73c4-33bc-48ae-b202-17f7d90f3cd1.png)
then when i open it in winrar it says this 
![image](https://user-images.githubusercontent.com/117794886/200731605-90e957d2-8beb-42a4-892e-d9ef627bb0f0.png)
 and yes i extracted it

**Comment by bigjayrbk3** [comment]
nd also this 
![image](https://user-images.githubusercontent.com/117794886/200732371-458943c4-7fd0-47f3-a22f-66400ce68b16.png)

**Comment by bigjayrbk3** [comment]
and this bru 
![image](https://user-images.githubusercontent.com/117794886/200733298-39b116df-dc03-4052-b975-93112df29616.png)

**Comment by ic3w0lf22** [comment]
download the release not the source code
