### ISSUE TITLE
issue with auto relaunch

### ISSUE THREAD

**Issue by BAYUKA123s** [ic3w0lf22/Roblox-Account-Manager#125]
when i try to put on auto relaunch so just incase i crash it keeps opening roblox even tho im in any help/suggestions
![image](https://user-images.githubusercontent.com/118318055/202049228-e8402ee0-c851-449e-b954-cf3b0ab77d8c.png)
 like this it does it over and over

**Comment by ic3w0lf22** [comment]
did you set up nexus correctly?

**Comment by BAYUKA123s** [comment]
> did you set up nexus correctly?

Yea but I just keeps going I added my key in it too

**Comment by ic3w0lf22** [comment]
Try with the latest version

**Comment by Toga247** [comment]
> Try with the latest version

latest version does not open at all
