### ISSUE TITLE
Cant auto update

### ISSUE THREAD

**Issue by Saberton1** [ic3w0lf22/Roblox-Account-Manager#129]
When i try to auto update it says: Something went wrong! Access to the path C:\Users\user\Downloads\ RBX Alt Manager\x86\locales is denied.

**Comment by ic3w0lf22** [comment]
try with the [latest version released 8 minutes ago](https://github.com/ic3w0lf22/Roblox-Account-Manager/releases/download/3.4/Roblox.Account.Manager.3.4.zip)
