### ISSUE TITLE
Autoupdate

### ISSUE THREAD

**Issue by ItsGamingFactYT** [ic3w0lf22/Roblox-Account-Manager#130]
When i open RBX account manager it gets stuck at autoupdate 
![Capture](https://user-images.githubusercontent.com/118593678/202840136-64ab177e-b18d-400f-b203-7352ac9d2ead.PNG)

**Comment by ic3w0lf22** [comment]
what os?

**Comment by ItsGamingFactYT** [comment]
windows 7


> what os?

windows 7
64 bit

**Comment by ItsGamingFactYT** [comment]
nvm it is working in older version 3.3.2
