### ISSUE TITLE
Favorite games deleted upon exiting application

### ISSUE THREAD

**Issue by FunnyMonkeyBaz** [ic3w0lf22/Roblox-Account-Manager#134]
Saving works while the program hasn't been closed yet, but the second i close it and re-open it to check if its saved it will be gone

**Comment by ic3w0lf22** [comment]
thank you for reporting this, this has been fixed with the latest update, simply launch the autoupdater or [download manually](https://github.com/ic3w0lf22/Roblox-Account-Manager/releases/0.0)

this update won't notify users about an update
