### ISSUE TITLE
Username not showing in Account Control.

### ISSUE THREAD

**Issue by exepted** [ic3w0lf22/Roblox-Account-Manager#135]
No matter how many accounts I add it wont pop up in Account Control. I'm not sure if its just my problem and if so please help.

**Comment by exepted** [comment]
![helppls](https://user-images.githubusercontent.com/119388365/205423147-0c6519e4-9790-40ef-87fe-21ef28d54a58.png)

**Comment by ic3w0lf22** [comment]
drag and drop the names in.
