### ISSUE TITLE
Huge freezes and delay when interacting with the UI

### ISSUE THREAD

**Issue by phoriah** [ic3w0lf22/Roblox-Account-Manager#136]
After the release of recent updates, (3.4 and 3.4.1), the user experience has not been smooth at all for me. Whenever I click on **_any_** buttons, the delay between click and response could be up to few seconds, very sluggish and uncomfortable. If you need my system specs or anything else please tell me.
Hopefully this will get fixed,
Thanks,
P.

**Comment by ic3w0lf22** [comment]
can you open settings, go to developer tab, and checking the "Disable Image Loading" checkbox, restart, then let me know if thats what causing poor performance?

**Comment by ic3w0lf22** [comment]
Can you send me your PC specs and `RAMSettings.ini` file? RAMSettings.ini contains nothing important so it's fine to send it through github
