### ISSUE TITLE
CefSharp.Core.Runtime.DLL It is erased by the Antivirus of Windows

### ISSUE THREAD

**Issue by Nexosebas** [ic3w0lf22/Roblox-Account-Manager#14]
What happens is that the Antivirus detects Wacatac.b! Ml as a Trojan, when restoring it and trying to reopen Roblox Account Manager an error occurs that does not allow the application to run even if you uninstall it and reinstall it, it stays that way until you format the Computer.

Please someone help me

![2021-07-01 (2)](https://user-images.githubusercontent.com/86798280/124168354-a2f0a300-da6a-11eb-8761-8ae0066448e6.png)
![2021-07-01 (3)](https://user-images.githubusercontent.com/86798280/124168357-a3893980-da6a-11eb-85a0-d600bcbf0d39.png)
![2021-07-01](https://user-images.githubusercontent.com/86798280/124168358-a421d000-da6a-11eb-8141-68d327b2c2f4.png)

**Comment by fijibeng** [comment]
You could add an exclusion for the folder Roblox Account Manager is in, that's what I did. But I would still like to know why WinDef is triggering on this.

**Comment by Nexosebas** [comment]
Because Roblox Account Manager runs roblox which is a .Exe program and
therefore detects it as a Trojan

**Comment by Nexosebas** [comment]
> You could add an exclusion for the folder Roblox Account Manager is in, that's what I did. But I would still like to know why WinDef is triggering on this.
> 
> If you couldn't be bothered to sign into your accounts again, just copy AccountData.json in the Roblox Account Manager folder to somewhere else, and after you have redownloaded RAM, search for "windows security" in your search bar, go to "virus and threat protection," "virus and threat protection settings" and scroll down until you see "add or remove exclusions." Hit "add exclusion" and then folder, and add the folder Roblox Account Manager is in. You can copy AccountData.json back into the same folder.

**Comment by Nexosebas** [comment]
> You could add an exclusion for the folder Roblox Account Manager is in, that's what I did. But I would still like to know why WinDef is triggering on this.
> 
> If you couldn't be bothered to sign into your accounts again, just copy AccountData.json in the Roblox Account Manager folder to somewhere else, and after you have redownloaded RAM, search for "windows security" in your search bar, go to "virus and threat protection," "virus and threat protection settings" and scroll down until you see "add or remove exclusions." Hit "add exclusion" and then folder, and add the folder Roblox Account Manager is in. You can copy AccountData.json back into the same folder.

Bro I Format my PC, Disable Windows Defender when I did that, install Roblox Acc Manager, it was fine, turn off the PC And again the error occurred, it could not have been the antivirus ...
