### ISSUE TITLE
Trojan?

### ISSUE THREAD

**Issue by JustDevT** [ic3w0lf22/Roblox-Account-Manager#144]
I scanned at Virus total and it showed that it has 3 viruses, I looked at the source code I found nothing, I dont know if I missed some parts of the source code. I dont know its false positive or not?

**Comment by ic3w0lf22** [comment]
compile it yourself and you will most likely get the same results from an antivirus.

**Comment by Entidy** [comment]
only 3 results all from no-name anti-viruses is a false positive. you only have to worry if something is a virus if it is 5-10 positives.
