### ISSUE TITLE
attempt to index a nil with 'Connected'

### ISSUE THREAD

**Issue by tigra323** [ic3w0lf22/Roblox-Account-Manager#149]
Nexus.lua in autoexec folder, script 
![изображение](https://user-images.githubusercontent.com/57480752/209520905-47633572-2abb-4be6-9e76-e8af03ea8ea3.png)
gives an error
![изображение](https://user-images.githubusercontent.com/57480752/209521226-e9742b13-6ebb-4b7a-b955-4958d9237d8c.png)
Using krnl

**Comment by ic3w0lf22** [comment]
krnl is unsupported
