### ISSUE TITLE
Hostname is invalid

### ISSUE THREAD

**Issue by ReQiuYTPL** [ic3w0lf22/Roblox-Account-Manager#153]
I can't access the Web server from outside, i have opened my port, but it says that my hostname is invalid, on localhost it is working fine.
I have also tried to change the port, but nothing changed

![image](https://user-images.githubusercontent.com/56265894/210608379-8fee8403-a986-4018-87c9-62a09dfe7f27.png)
![image](https://user-images.githubusercontent.com/56265894/210608389-7f749745-9493-4c81-ae61-188294eb2d71.png)

**Comment by phyouthcenter1** [comment]
If you are using a domain name then you should use an A record to point to your IP instead of host names. It does the same.

**Comment by ic3w0lf22** [comment]
The local web server isn't accessible from outside networks, I'll probably add an option to allow it.
