### ISSUE TITLE
two RAM in same time

### ISSUE THREAD

**Issue by zeussama** [ic3w0lf22/Roblox-Account-Manager#158]
ı tried it with Sandboxie app but roblox didnt work. ı want that because ı will use spesific "Relaunch delay per account" and "launcher delay" for each roblox server.
ı cant join gpo with low delay, ı must do it 70-80 secs to join gpo if ı use 2+ accounts
ı cant just use "70-80 secs" delay because ı joining on diffrent roblox servers. ı just need 2 RAM in same time
![error](https://user-images.githubusercontent.com/67295723/212404970-a276a8c0-b091-42b8-8187-6a8b69557f1b.png)
![delay](https://user-images.githubusercontent.com/67295723/212405049-2c5012df-9bc7-4539-b8e5-9b88fe1e27d3.png)

**Comment by ic3w0lf22** [comment]
i'm assuming roblox added some anti myltiaccounting thing because now only the last joined account can teleport to different servers, there is probably nothing i can do about it.
