### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Szymonidas1112** [ic3w0lf22/Roblox-Account-Manager#159]
When it tries to extract files it just crashes on the auto update.

**Comment by Shawsterr** [comment]
happened to me too

**Comment by ic3w0lf22** [comment]
try again, then once it crashes, open a file explorer, click the path at the top, and put `%localappdata%\CrashDumps`, then upload the latest crash dump for "AutoUpdate.exe"

**Comment by Szymonidas1112** [comment]
https://anonymfile.com/YPgp8/auto-updateexe11496.dmp

**Comment by ic3w0lf22** [comment]
Are you still having this issue?

**Comment by Szymonidas1112** [comment]
yes

**Comment by ic3w0lf22** [comment]
message me on discord ic3#0001, reply with your discord so i know who to accept

**Comment by Szymonidas1112** [comment]
coolguy#4338
