### ISSUE TITLE
RAM stops responding every 5 seconds, spawns 2 Synapses and makes them crash

### ISSUE THREAD

**Issue by TheJailerOfTime** [ic3w0lf22/Roblox-Account-Manager#160]

**Comment by XSSBacon** [comment]
This thing is kinda buggy ngl

**Comment by phyouthcenter1** [comment]
if you are using synapse x's custom launcher instead of Roblox try turning it off because RAM might not recognize it as Roblox therefore relaunching it and then doesnt recognize that and relaunches it.

**Comment by phyouthcenter1** [comment]
The setting should be auto launch which is what should be off in the trial

**Comment by ic3w0lf22** [comment]
not enough details provided

**Comment by phyouthcenter1** [comment]
That is a lot of detail. What more do you need?

**Comment by phyouthcenter1** [comment]
I get the same problem now.
