### ISSUE TITLE
Accounts get logged out once another account launches

### ISSUE THREAD

**Issue by basali111** [ic3w0lf22/Roblox-Account-Manager#164]
There's currently an issue where an account gets logged out once a new account gets launched through the manager. You don't get kicked from the game but this makes it so you can't teleport anywhere else within the game of the logged out account. You can reproduce this by leaving the game, which shows the login screen. This is the cause of the teleport restricted issue.

**Comment by ic3w0lf22** [comment]
not an account manager bug

**Comment by basali111** [comment]
so is this a roblox issue you can't fix? i only use RAM, nothing else.

**Comment by ic3w0lf22** [comment]
yes. pretty sure its something to do with preventing multi accounting

**Comment by basali111** [comment]
okay, thats sad to hear. However if i relog in the account thats logged out it fixes the issue until the next time i launch those accounts. don't know if that changes anything or if its still unfixable.
