### ISSUE TITLE
Error code 773

### ISSUE THREAD

**Issue by Chasedcrown** [ic3w0lf22/Roblox-Account-Manager#165]
When i try to teleport to a story mode i always get the error code "teleport failed" and its always when im using multiple accounts at once, how do i fix this? and only the account that was opened first manages to get in.

**Comment by Abyssalfire** [comment]
I'm having the same issue, I've tried Reinstalling roblox, moving it to a clean SSD, clearing DNS, Winsock all that, Different accounts, Wifi and ethernet, 13+ and under 13 accounts, Changed my firewall settings, Anti-virus settings. still to no avail.

**Comment by ic3w0lf22** [comment]
not an account manager issue
