### ISSUE TITLE
Multiple roblox instances getting logged out

### ISSUE THREAD

**Issue by oTradeMark** [ic3w0lf22/Roblox-Account-Manager#166]
When you launch multiple roblox account instances, all accounts except the most recent account launched is logged out. This creates a problem for games where you load into a new server for different areas of the game because only the most recently launched account will teleport.

**Comment by ic3w0lf22** [comment]
not an account manager issue

**Comment by ic3w0lf22** [comment]
found a bypass to this issue, out now in update 3.5
