### ISSUE TITLE
Red Dot (nexus not working)?

### ISSUE THREAD

**Issue by Haruie** [ic3w0lf22/Roblox-Account-Manager#167]
i have been trying for sometime now but whatever i do, the red dot doesnt turn green.

1- my nexus lua is in my auto exec.
2- i use synapse.
3- i also tried manually executing it but it still doesnt turn it green.

i just cant figure it out someone please help 😞

**Comment by ic3w0lf22** [comment]
Probably a network issue.

Q: I have Synapse X and Nexus.lua in the autoexec folder, but will sometimes still fail and cause my accounts to automatically relaunch repeatedly 
A: Your network may be unstable, or github may be down. To fix this, download the actual nexus script (linked below), and replace the existing Nexus.lua file with the one you downloaded

https://raw.githubusercontent.com/ic3w0lf22/Roblox-Account-Manager/master/RBX%20Alt%20Manager/Nexus/Nexus.lua
