### ISSUE TITLE
Stuck at "Current Place" no matter what game ID I put

### ISSUE THREAD

**Issue by justarandompersonongithub** [ic3w0lf22/Roblox-Account-Manager#168]
Stuck at "Current Place" no matter what game ID I put, as title stats
Also can't search for games anymore as it shows nothing back

**Comment by justarandompersonongithub** [comment]
@ic3w0lf22

**Comment by ic3w0lf22** [comment]
Roblox removed the original `api.roblox.com` endpoints, this will be fixed in the next update
