### ISSUE TITLE
No Account were loaded.

### ISSUE THREAD

**Issue by Eth030** [ic3w0lf22/Roblox-Account-Manager#169]
![grafik](https://user-images.githubusercontent.com/6024410/223540991-6085091a-9d6b-4c11-8a45-4295a4920ee1.png)
I am getting this issue after running this without problem for two weeks.
After pressing on yes, i get following error:
![grafik](https://user-images.githubusercontent.com/6024410/223541143-6f244d67-2c82-44d3-87ba-eee9d2192f3e.png)
This is really an issue, i dont want to re-enter all the accounts.
Can anyone please advise?

**Comment by ic3w0lf22** [comment]
The backup file is there incase the main file gets corrupted/overwritten with no data.

There is no way to recover your `AccountData.json` unless you are on the same PC the file originated from or you decrypted it and stored it safely. Hardware changes will probably affect how the encryption works and will prevent you from loading your accounts.

**Comment by Eth030** [comment]
Ahhh Males Sense Jam in en virtual Environment Hwid Chang es regularly, thanks gor Feedback.Von meinem iPhone gesendetAm 10.03.2023 um 20:49 schrieb ic3w0lf22 ***@***.***>:﻿
The backup file is there incase the main file gets corrupted/overwritten with no data.
There is no way to recover your AccountData.json unless you are on the same PC the file originated from or you decrypted it and stored it safely. Hardware changes will probably affect how the encryption works and will prevent you from loading your accounts.
