### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by maksimls1** [ic3w0lf22/Roblox-Account-Manager#171]
I turned on the roblox watcher and after launching the account, the RAM just crashes, and without a roblox watcher it is impossible to put afk farm because of the roblox beta, I do not know what to do with it

**Comment by ic3w0lf22** [comment]
Look for a crash dump file in `%localappdata\CrashDumps` called `RBX Alt Manager.exe.dmp`, and upload it here or to my discord DMs (ic3#0001)

**Comment by maksimls1** [comment]
okay

**Comment by maksimls1** [comment]
I hope you'll figure it out
