### ISSUE TITLE
Failed to detect Visual Studio Redistributable

### ISSUE THREAD

**Issue by joshnothere** [ic3w0lf22/Roblox-Account-Manager#173]
whenever i try opening the application it always pops up with this
![image](https://user-images.githubusercontent.com/128186123/226024737-92fe23ee-67e4-4898-8142-d2c825afc5ac.png)
but I already installed the vcredit thing right here
![image](https://user-images.githubusercontent.com/128186123/226025208-b09725b1-3a6b-407a-8e10-0da1181b211a.png)
I have 0 idea why this is happening

**Comment by hutirok** [comment]
i got same error and  dont know how to fix it!

**Comment by ic3w0lf22** [comment]
Delete the x86 folder or completely reinstall account manager
