### ISSUE TITLE
Cant join my own private server

### ISSUE THREAD

**Issue by EPICXE** [ic3w0lf22/Roblox-Account-Manager#178]
Whenever I try to make it join my own private server I keep getting an error saying I do not have permission.

**Comment by seronero** [comment]
if you're trying to join on your alt, go into your alt's privacy settings, and change "who can invite me to private servers" to everyone

**Comment by EPICXE** [comment]
Except I'm trying to join on my main, not an alt

**Comment by prljav** [comment]
make sure all of your accounts are over 13!
