### ISSUE TITLE
Auto Close if there are more Roblox processes than specified value

### ISSUE THREAD

**Issue by phoriah** [ic3w0lf22/Roblox-Account-Manager#180]
The default value being the amount of accounts with Auto Relaunch enabled (In Account Control)
Reason: When Roblox updates it tends to break **_things_** for some time resulting in the app relaunching accounts endlessly until the PC can't handle any more.

**Comment by DaveyWar** [comment]
This is a great idea

**Comment by ic3w0lf22** [comment]
Added in 3.6
