### ISSUE TITLE
Make Auto Close only close Roblox proccesses launched from Auto Launch and not from elsewhere (if possible)

### ISSUE THREAD

**Issue by phoriah** [ic3w0lf22/Roblox-Account-Manager#185]
By elsewhere I mean Main window of RAM, Browsers, etc. (If it's only possible with RAM then that works too!)

**Comment by ic3w0lf22** [comment]
Added a better alternative automatically closing old instances of an account as long as it was launched with account manager. If this feature is still wanted, just reply here and I'll probably add it.

**Comment by ic3w0lf22** [comment]
In release 3.6.1, I've made roblox watcher completely ignore the window that is currently [focused](https://github.com/ic3w0lf22/Roblox-Account-Manager/blob/93ee8140d5168df62ceabc25f58f759bd07bde3b/RBX%20Alt%20Manager/Classes/RobloxWatcher.cs#L65) allowing you to do anything on any account manually without having to change settings around
