### ISSUE TITLE
App Window Ridiculously Oversized

### ISSUE THREAD

**Issue by DAMIANOO9** [ic3w0lf22/Roblox-Account-Manager#187]
![image](https://user-images.githubusercontent.com/50180031/230728281-65818491-2c79-4d49-8ae7-5f5657eef39a.png)
Not sure what is causing this but whenever I open this app (once a week) this happens.
I've found a fix of reinstalling but it's getting annoying having to reinstall and add all 9 accounts every week.
If you have any tips on how to prevent this, please let me know.

**Comment by ic3w0lf22** [comment]
Q: Fonts are incorrectly scaled
A: Close RAM, open RAMSettings.ini, change ScaleFonts=true to ScaleFonts=false, then restart RAM

Same applies for if the UI is massive, change WindowScale=X (X being the current value thats in there) to WindowScale=1
