### ISSUE TITLE
Waiting

### ISSUE THREAD

**Issue by AshDreemurrr** [ic3w0lf22/Roblox-Account-Manager#191]
the Roblox account manager auto update thingy that opens when u run RBX Alt manager  just says waiting and dosent progress
![image](https://user-images.githubusercontent.com/121996416/231443539-d191ce06-229e-40e2-8816-4cc96e6edda5.png)
im using windows 10

**Comment by ic3w0lf22** [comment]
You will have to manually download. I think this issue is caused by a network/certificate issue and have no idea how to fix it

**Comment by AshDreemurrr** [comment]
Alr thanks man I'll give it a go
