### ISSUE TITLE
Make an emoji support for GetDescription method

### ISSUE THREAD

**Issue by unsafe-rust** [ic3w0lf22/Roblox-Account-Manager#192]
actual description: 
![image](https://user-images.githubusercontent.com/68443801/231561704-57eee2c3-bb16-4707-8b46-6020a8492536.png)
and from using GetDescription I got:
![image](https://user-images.githubusercontent.com/68443801/231561854-cc79da0b-6b33-4ded-aa70-333c11d176b8.png)

**Comment by ic3w0lf22** [comment]
Fixed in next version

**Comment by ic3w0lf22** [comment]
Fixed in 3.6
