### ISSUE TITLE
Joining user Issue

### ISSUE THREAD

**Issue by Robomnz** [ic3w0lf22/Roblox-Account-Manager#196]
Ive tried this with diff accounts and even tried reinstalling roblox account manager but joining people that are currently ingame will boot up roblox and say this even though the user is ingame with joins on and we are friended. this happens every time i try to join anyone on roblox using the username joins.
![image](https://user-images.githubusercontent.com/34904608/232923512-c6d6b5a5-595e-407f-9e8a-56e08089af1a.png)

**Comment by ic3w0lf22** [comment]
they have their joins off or aren't in game
