### ISSUE TITLE
Shutting Down Roblox

### ISSUE THREAD

**Issue by NikoMikoNii** [ic3w0lf22/Roblox-Account-Manager#199]
Whenever I try to join in on another account the roblox client says shutting down roblox. you cant use 2 accounts anymore

**Comment by Noname7865** [comment]
I got the same issue, any idea to fix this?

**Comment by RichardGamings** [comment]
I have the same issue. When i use the Roblox Account Manager, when i try to have 2 instances on the background, one just tries to kill the other instance before entering the game. i dont know why. You explained it perfectly.

**Comment by RichardGamings** [comment]
The problem started Yesterday for me, when my Main Account got a Roblox Update. ever since then it basically didnt allow me to run 2 instances of roblox.
You could use the Microsoft Store Roblox + Website Roblox for now. They count has seperate instances and doesnt kill the other instance.

**Comment by xXNephowXx** [comment]
Is there any way to fix it yet?

**Comment by Austin1234321** [comment]
yeahhh

**Comment by ic3w0lf22** [comment]
launch all your accounts from account manager, not one from the browser and another from account manage.r
