### ISSUE TITLE
Accounts stored aren't encrypted

### ISSUE THREAD

**Issue by Mudock-Yatho** [ic3w0lf22/Roblox-Account-Manager#2]
Accounts are stored in plaintext within a json file, they should be at least encrypted so that if someone steals the stored file it won't be as easy to recover the cookies.

**Comment by xXGokyXx** [comment]
> Accounts are stored in plaintext within a json file, they should be at least encrypted so that if someone steals the stored file it won't be as easy to recover the cookies.

if someone had access to your computer that allowed them to specifically steal any plain text files they wanted, I think roblox cookies would be the least of your worry

**Comment by abrahampo1** [comment]
> > > Accounts are stored in plaintext within a json file, they should be at least encrypted so that if someone steals the stored file it won't be as easy to recover the cookies.
> > 
> > 
> > if someone had access to your computer that allowed them to specifically steal any plain text files they wanted, I think roblox cookies would be the least of your worry
> 
> Still doesn't excuse the fact that your cookies are stored in plain-text. Also it would matter if someone stole my cookies due to having thousands of USD worth of dev-exable robux on my account.
> Adding salted passwords with any form of encryption should be easy enough to add anyways, no reason not to.

Do that and pull request it

**Comment by ic3w0lf22** [comment]
This issue is now resolved in [Update 2.5](https://github.com/ic3w0lf22/Roblox-Account-Manager/releases/tag/2.5)
