### ISSUE TITLE
roblox screen

### ISSUE THREAD

**Issue by nicholvss** [ic3w0lf22/Roblox-Account-Manager#201]
my roblox screen is too big even after being minimised and i cant fit like example 5 screens at once as each of the roblox tabs are too big.

**Comment by ic3w0lf22** [comment]
buy a bigger monitor

this is an excellent choice as you can fit up to 60 roblox clients on one screen: https://www.dell.com/en-us/shop/dell-ultrasharp-32-8k-monitor-up3218k/apd/210-alez/monitors-monitor-accessories

**Comment by nicholvss** [comment]
> buy a bigger monitor
> 
> this is an excellent choice as you can fit up to 60 roblox clients on one screen: https://www.dell.com/en-us/shop/dell-ultrasharp-32-8k-monitor-up3218k/apd/210-alez/monitors-monitor-accessories

i have a 27 inch monitor 240hz and im not buying a monitor for that. im only want to run
 4-6 accounts at once.

**Comment by ic3w0lf22** [comment]
and how exactly do you expect me to fix roblox not allowing the window to be less than 800x600 pixels

**Comment by nicholvss** [comment]
> and how exactly do you expect me to fix roblox not allowing the window to be less than 800x600 pixels

but everyone else has no problem with it as when they load the roblox up it is a small tab unless their monitor is 2x as big as mine

**Comment by nicholvss** [comment]
> > buy a bigger monitor
> > this is an excellent choice as you can fit up to 60 roblox clients on one screen: https://www.dell.com/en-us/shop/dell-ultrasharp-32-8k-monitor-up3218k/apd/210-alez/monitors-monitor-accessories
> 
>if a 32 inch monitor can fit 60 roblox clients on one screen then how come my 27 inch monitor on native res cant even fit 3 on one screen??

**Comment by ic3w0lf22** [comment]
who is "everyone else"
not everyone has the same exact monitor
a monitor can be 27in but the resolution could be 3840x2160 allowing the window to be much smaller on an equally sized monitor

**Comment by nicholvss** [comment]
> so the solution to it is to change my resolution much higher?

**Comment by ic3w0lf22** [comment]
you can do that but your gpu or monitor may not support higher resolutions

**Comment by nicholvss** [comment]
> you can do that but your gpu or monitor may not support higher resolutions

what are some other high resolutions higher than 2k?

**Comment by nicholvss** [comment]
> you can do that but your gpu or monitor may not support higher resolutions

https://prismplus.sg/products/prism-x270-240hz this is my monitor
