### ISSUE TITLE
I'm using laptop window 7

### ISSUE THREAD

**Issue by EthanOrThanh** [ic3w0lf22/Roblox-Account-Manager#204]
uhh i found a error, when i open the roblox manager account. its always like 100% stop working, i tried many ways, redownload and open file again and it still get stop working when i open the roblox manager account.

**Comment by hdifheidsk** [comment]
im having this issue also and im on windows 7, so i think it's not compatible for windows 7 sadly

**Comment by ic3w0lf22** [comment]
as long as you download manually and have the latest vcredist installed, it should work fine.
