### ISSUE TITLE
Multiple Instance not working anymore after the latest update.

### ISSUE THREAD

**Issue by jsthrfrstff** [ic3w0lf22/Roblox-Account-Manager#205]
just now when I opened it and updated it, I tried opening multiple accounts like what I always did in the past few months, but now it force closes the most recent instance after instance and in the end the last game instance remains.

**Comment by ic3w0lf22** [comment]
read the update

**Comment by jsthrfrstff** [comment]
I was looking for the update log here but it was on discord lol. fixed it, thank you.
