### ISSUE TITLE
RBX Alt Manager automatically removes EnableMultiRbx=true from RAMSettings.ini

### ISSUE THREAD

**Issue by Bvcv12** [ic3w0lf22/Roblox-Account-Manager#208]
When launching RBX Alt Manager.exe, the EnableMultiRbx=true line that I added via Notepad under the [General] section into the RAMSettings.ini gets automatically deleted. It just suddenly disappears. As such, I have been unable to launch multiple instances of Roblox at all since this new update 3.5.1 came out. Before this update, the multiple instances of Roblox successfully worked, but now it's broken.

Please have there be a way that keeps the EnableMultiRbx=true remembered in the RAMSettings without having to re-add it each time. Does it matter where it's placed in the [General] list, like at the top vs the bottom?

**Comment by ic3w0lf22** [comment]
close the account manager first then try again

**Comment by Bvcv12** [comment]
> close the account manager first then try again

Thanks. The program auto updated just now and the multiple instances works again. And the EnableMultiRbx=true stays on there now. Keep up the good work! :D
