### ISSUE TITLE
The wait Completed due to an abandoned mutex. [Not starting Properly]

### ISSUE THREAD

**Issue by ItoshiTeruz** [ic3w0lf22/Roblox-Account-Manager#21]
**I have absolutely no clue what this error is and not too sure how I can fix it?**
**Using latest update**

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(TimeSpan timeout, Boolean exitContext)
   at RBX_Alt_Manager.AccountManager.AccountManager_Shown(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
RBX Alt Manager
    Assembly Version: 1.0.0.0
    Win32 Version: 2.4.0.0
    CodeBase: file:///C:/Users/Worth/Desktop/Roblox.Account.Manager.2.3.1/RBX%20Alt%20Manager.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
ObjectListView
    Assembly Version: 2.9.1.1072
    Win32 Version: 2.9.1.0
    CodeBase: file:///C:/Users/Worth/Desktop/Roblox.Account.Manager.2.3.1/ObjectListView.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
RestSharp
    Assembly Version: 106.11.8.0
    Win32 Version: 106.11.8
    CodeBase: file:///C:/Users/Worth/Desktop/Roblox.Account.Manager.2.3.1/RestSharp.DLL
----------------------------------------
CefSharp.WinForms
    Assembly Version: 91.1.211.0
    Win32 Version: 91.1.211.0
    CodeBase: file:///C:/Users/Worth/Desktop/Roblox.Account.Manager.2.3.1/CefSharp.WinForms.DLL
----------------------------------------
CefSharp.Core
    Assembly Version: 91.1.211.0
    Win32 Version: 91.1.211.0
    CodeBase: file:///C:/Users/Worth/Desktop/Roblox.Account.Manager.2.3.1/CefSharp.Core.DLL
----------------------------------------
CefSharp
    Assembly Version: 91.1.211.0
    Win32 Version: 91.1.211.0
    CodeBase: file:///C:/Users/Worth/Desktop/Roblox.Account.Manager.2.3.1/CefSharp.DLL
----------------------------------------
CefSharp.Core.Runtime
    Assembly Version: 91.1.211.0
    Win32 Version: 91.1.211
    CodeBase: file:///C:/Users/Worth/Desktop/Roblox.Account.Manager.2.3.1/CefSharp.Core.Runtime.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///C:/Users/Worth/Desktop/Roblox.Account.Manager.2.3.1/Newtonsoft.Json.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by ic3w0lf22** [comment]
Is this error still happening with the latest version?

**Comment by ItoshiTeruz** [comment]
> Is this error still happening with the latest version?

Nope it seems to be fixed in latest version, Must have been a problem with my computer at the time, Not too sure?
