### ISSUE TITLE
whys it say virus?

### ISSUE THREAD

**Issue by robloxUser827** [ic3w0lf22/Roblox-Account-Manager#210]
last update didnt have a virus warning could you explain to me why, is it like due to changing game mechanics or whatever?

**Comment by ic3w0lf22** [comment]
interesting, might be because of the very scuffed way i updated the program. i opened it in dnspy and modified the ilcode to change DisableMultiRbx to EnableMultiRbx then i used resource hacker to change the product version.

i'll try and get an update out today that isn't scuffed

**Comment by robloxUser827** [comment]
ok thank you because im new to alt account manager stuff and i want it to be a fun expierence also i have stuff on my alt accounts i cant get off there

**Comment by ic3w0lf22** [comment]
roblox account manager has and will probably always be detected as a virus since it is not signed or developed by a legitimate company.
