### ISSUE TITLE
how do i turn off defender on something different than windows 10?

### ISSUE THREAD

**Issue by robloxUser827** [ic3w0lf22/Roblox-Account-Manager#211]
i don't know what my computer is but i have the same stuff as it looks like but when i click on the security it says open app

**Comment by robloxUser827** [comment]
i just checked and i have trelix security and i opened the app and i cant turn it off

**Comment by robloxUser827** [comment]
im not used to git hub yet i gotta find the tab to find the older versions

**Comment by robloxUser827** [comment]
okay so i did something different that i haven't been doing i installed the auto update before i ran the alt account manager

**Comment by robloxUser827** [comment]
what were you updating it for today anyways?

**Comment by ic3w0lf22** [comment]
google will answer your questions

"how do i disable <x> antivirus"
"how do i add an exception <x> antivirus

**Comment by robloxUser827** [comment]
> google will answer your questions
> 
> "how do i disable antivirus" "how do i add an exception antivirus

im talking about into the settings in the alt account manager menu, sorry i wasnt very clear
