### ISSUE TITLE
Roblox account manager being taken down

### ISSUE THREAD

**Issue by Austin1234321** [ic3w0lf22/Roblox-Account-Manager#218]
I saw the DM between Janey and the roblox staff saying that running multiple instances on the same machine is considered "malicious behavior" and what-not. Basically making it so we can't run multiple roblox accounts at the same time. Is there a possible fix and will there be for this page? I don't really know how this works in the first place, but It's still a tool I actively use nonetheless. This is very unfortunate news.

**Comment by ic3w0lf22** [comment]
nobody ever said account manager was being taken down. you can enable multi roblox yourself at your own risk and currently there have been no reported/confirmed bans for using multiple clients

**Comment by xXNephowXx** [comment]
Is there a way to fix it not working?
