### ISSUE TITLE
Api always responds "Invalid Password" using LaunchAccount

### ISSUE THREAD

**Issue by TheCrazyInsanity** [ic3w0lf22/Roblox-Account-Manager#22]
No format here, but here is what i am sending a get request to if that matters

http://localhost:7963/LaunchAccount?Account=morganwilson28&PlaceId=2262441883&JobId=bbf92a34-8358-4fb4-a1cf-29332840cac1&Password=sus

and here is the config

[General]
SavedPlaceId=2262441883
DisableAutoUpdate=false
[Developer]
DevMode=true
EnableWebServer=true
[WebServer]
WebServerPort=7963
AllowGetCookie=true
AllowGetAccounts=true
AllowLaunchAccount=true
AllowAccountEditing=true
Password=sus
EveryRequestRequiresPassword=true

**Comment by ic3w0lf22** [comment]
Your password must be at least 6 characters long
