### ISSUE TITLE
the first roblox tab closing after the new one appears (I had the roblox program closed)

### ISSUE THREAD

**Issue by Johnaboy** [ic3w0lf22/Roblox-Account-Manager#220]

**Comment by Johnaboy** [comment]
as soon as I press join server and wait, my second alt joins but my first alts leaves.

**Comment by 1stub** [comment]
I am having this issue also

**Comment by EasyPeezyLemonSqueezy** [comment]
u gotta enable the setting

**Comment by Austin1234321** [comment]
> 

? ive never had to enable a setting before

**Comment by giiz9** [comment]
what setting do you need to enable

**Comment by EasyPeezyLemonSqueezy** [comment]
> what setting do you need to enable
go into RAMSettings.ini and change false to true

**Comment by GoldenCarrotMLP** [comment]
> > what setting do you need to enable
> > go into RAMSettings.ini and change false to true

There are like 21 settings that can be changed to either true or false. Please be more specific

**Comment by EasyPeezyLemonSqueezy** [comment]
thought it would be common sense its called multirblx lol
