### ISSUE TITLE
Is this compatible with Windows 7?

### ISSUE THREAD

**Issue by hdifheidsk** [ic3w0lf22/Roblox-Account-Manager#223]
I'm on windows 7 and when I download it, it just doesn't and keep says "Waiting"

https://streamable.com/li54i1

**Comment by ic3w0lf22** [comment]
download manually: https://github.com/ic3w0lf22/Roblox-Account-Manager/releases/tag/0.0

**Comment by Vlogcksz** [comment]
> download manually: https://github.com/ic3w0lf22/Roblox-Account-Manager/releases/tag/0.0

I downloaded this but whenever i open r.a.m this pops up..
![image](https://github.com/ic3w0lf22/Roblox-Account-Manager/assets/123242021/c592b91a-0146-4f8c-a384-6726d51fc248)

**Comment by ic3w0lf22** [comment]
download the latest x86 vcredist from https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
