### ISSUE TITLE
Experience restricted

### ISSUE THREAD

**Issue by Jojoisdagoat** [ic3w0lf22/Roblox-Account-Manager#227]
Everytime i try to launch a game using Roblox Account Manager it kicks me out of the game and says "This experience is restriced". I was wondering if there was a way to solve this problem

**Comment by South2x** [comment]
SAME!

**Comment by olegake10** [comment]
SAME!

**Comment by laurahburg** [comment]
mine is doing the same thing :(

**Comment by avinpoopy** [comment]
Me too
