### ISSUE TITLE
OP auto clicker not working with RAM.

### ISSUE THREAD

**Issue by Sribot9** [ic3w0lf22/Roblox-Account-Manager#231]
I don't know what it is, but when playing roblox using 2 accounts with RAM, No imputs register from OP auto clicker. pressing F6 doesn't turn it on, but swapping into a different program, pressing F6 works. when its on, it clicks everywhere EXCEPT in roblox. it works on other apps, but not roblox. anyone know what I can do?

**Comment by ic3w0lf22** [comment]
are you running account manager as admin? i dont know how this auto clicker you speak of works but it may not have permission to interact with roblox or it could be hyperion blocking it
