### ISSUE TITLE
Error: failed to launch roblox

### ISSUE THREAD

**Issue by Lancer498** [ic3w0lf22/Roblox-Account-Manager#232]
![image](https://github.com/ic3w0lf22/Roblox-Account-Manager/assets/58575189/e6813fc6-6ea4-46b1-a8ef-ef8b2f5207b2)
Translation for the text: 
"Reference of object not defined for a instance of a object in"

"line 659"

I've already installed the vcredists, and .NET framework just mysteriously doesn't want to install. I'm on windows 7

**Comment by ic3w0lf22** [comment]
make sure you have roblox installed
