### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by zkwik** [ic3w0lf22/Roblox-Account-Manager#240]
I open roblox first and alt manager still closes down the other roblox it doesnt work multiple robloxes at once

**Comment by genkroco** [comment]
you have to enable Multi roblox in the settings

**Comment by SuperSuperSuperFranky** [comment]
> you have to enable Multi roblox in the settings

I had to redownload Account manager recently, and I have the "EnableMultiRoblox=True" in my setting for the newest version. It does not allow me to have multiple instances anymore. It was working on the previous version I had, until that previous version stopped working altogether.

**Comment by ic3w0lf22** [comment]
read faq
