### ISSUE TITLE
This experience is restricted Issue

### ISSUE THREAD

**Issue by ayoGrox** [ic3w0lf22/Roblox-Account-Manager#242]
Every time when i want to use the program it tells me that the experience is restricted
![image](https://github.com/ic3w0lf22/Roblox-Account-Manager/assets/127602186/a6e55aa9-d36c-41d9-a612-e351c692b712)
come on man i just want to farm in game it doesn't say joining now or disconnected but where it says joining now it just says this experience is restricted

**Comment by ic3w0lf22** [comment]
won't fix til proper reproduction steps are provided
