### ISSUE TITLE
Unable to join the game with 1 player per server

### ISSUE THREAD

**Issue by 5sanek5** [ic3w0lf22/Roblox-Account-Manager#246]
I wanted to join a game (a universal time), where you first are put into a 1 player server, after that you can join normal servers. Nothing was happening when I was clicking "Join server" button. Is there a way to make accounts join different servers?

**Comment by MixerMineSwe** [comment]
Dont put in a private server code and they should be sent to diffrent servers it worked fine for me when i could use it on gpo
