### ISSUE TITLE
Help! Get an app to open this 'Roblox-player' link

### ISSUE THREAD

**Issue by haohao92-py** [ic3w0lf22/Roblox-Account-Manager#263]
Error 1:
![image](https://github.com/ic3w0lf22/Roblox-Account-Manager/assets/141325913/1bd5fabc-7b57-418a-b221-2190331caad0)
Error 2:
![image](https://github.com/ic3w0lf22/Roblox-Account-Manager/assets/141325913/96e3dc9b-1642-42de-b3e5-b18ed952e0a0)
Microsoft Store:
![image](https://github.com/ic3w0lf22/Roblox-Account-Manager/assets/141325913/48cb1d97-f47a-4fe3-8d98-4e0253f80321)

I can't access the game from Account Manager because I can't find the game in M Store, while I have it installed, thanks

**Comment by ic3w0lf22** [comment]
Download roblox or set up your accounts correctly using the UWP instance manager
