### ISSUE TITLE
Synapse not working with Roblox ACC Manager roblox instances

### ISSUE THREAD

**Issue by O390F** [ic3w0lf22/Roblox-Account-Manager#31]
why does roblox crash whenever u use synapse with roblox acc manager but then works normally without roblox acc manager it was working before? Please can you fix this issue. Thanks

**Comment by https404** [comment]
Make sure

- You have roblox beta disabled
- You are using the _Join Server_ Button

**Comment by O390F** [comment]
I have beta enabled and even if I use the join server option it does not
work

**Comment by Cohenisabro** [comment]
i have beta disabed and pressed join server but it closes out of the account i joined roblox on and opens the account i used from the alt manger

**Comment by Cohenisabro** [comment]
and synapse then crashes
