### ISSUE TITLE
Not usable at all.

### ISSUE THREAD

**Issue by BuggedManager** [ic3w0lf22/Roblox-Account-Manager#349]
Everytime I launch one account, If I launch another one, the one I just launched close. Nice software

**Comment by ic3w0lf22** [comment]
turn on multi roblox

**Comment by BuggedManager** [comment]
You think I did not do that? Im not stupid. It is on, and Yet when I launch another account, it updates roblox every single time, which close the other client.

**Comment by ic3w0lf22** [comment]
are you launching from another browser?

**Comment by BuggedManager** [comment]
Nope, same browser and everything. It is weird af and makes the program pointless

**Comment by BuggedManager** [comment]
roblox making it fucking awful to use alt accounts

**Comment by ic3w0lf22** [comment]
What I meant to say is: are you launching from a browser at all?

**Comment by ic3w0lf22** [comment]
If you launch from a browser at all, it will trigger a Roblox update since Roblox assigns specific versions to accounts for some reason. Launch exclusively from account manager and every account will stay on the same Roblox version.

**Comment by BuggedManager** [comment]
Alright, but how can I use a private server from the app itself, When I try, I get "This Experience is Restricted"

**Comment by ic3w0lf22** [comment]
Use the (latest version)[https://github.com/ic3w0lf22/Roblox-Account-Manager/releases/tag/3.7.1], not yet released due to some random crash I keep getting.

**Comment by BuggedManager** [comment]
Okay, thanks! btw ty for the quick response <3
