### ISSUE TITLE
Multi Roblox not working

### ISSUE THREAD

**Issue by N04HB0URG3015** [ic3w0lf22/Roblox-Account-Manager#350]
I have multi Roblox on but when I go to open a new account it closes the first account and launches the second.

**Comment by zenoooooon** [comment]
Same for me. I try deleting stuff and reinstalling them but it still doesn't work.

**Comment by FPHroblox** [comment]
Any update? Have you fixed it?

**Comment by EroZero** [comment]
Doesnt work for me aswell.

**Comment by N04HB0URG3015** [comment]
> Any update? Have you fixed it?

No I haven’t I’ve tried a lot of fixes but nothing is working

**Comment by Ogy** [comment]
It works for me in some combination, as I wrote in https://github.com/ic3w0lf22/Roblox-Account-Manager/issues/335
Now I've added next account, and it doesn't work with any older :(

**Comment by nullwinnertwo2** [comment]
I found a fix. Download the roblox app via microsoft store. Sign in and go onto any game and then send in the alts.

**Comment by Ogy** [comment]
> I found a fix. Download the roblox app via microsoft store. Sign in and go onto any game and then send in the alts.

Unfortunately, it doesn't work for me. I've tried both with it installed from the website and with everything uninstalled. RBX always downloads and installs the Roblox client itself.

**Comment by Wessendy** [comment]
> > I found a fix. Download the roblox app via microsoft store. Sign in and go onto any game and then send in the alts.
> 
> Unfortunately, it doesn't work for me. I've tried both with it installed from the website and with everything uninstalled. RBX always downloads and installs the Roblox client itself.

Delete robloxplayerinstaller.exe in roblox's folder, that should work

**Comment by N04HB0URG3015** [comment]
> > > I found a fix. Download the roblox app via microsoft store. Sign in and go onto any game and then send in the alts.
> > 
> > 
> > Unfortunately, it doesn't work for me. I've tried both with it installed from the website and with everything uninstalled. RBX always downloads and installs the Roblox client itself.
> 
> Delete robloxplayerinstaller.exe in roblox's folder, that should work

Omg thank you this worked
