### ISSUE TITLE
how do i join private servers with roblox account manager

### ISSUE THREAD

**Issue by XPIREDPIRED5** [ic3w0lf22/Roblox-Account-Manager#36]
how do i join private servers with roblox account manager

**Comment by soudblox** [comment]
Put the private server link in Job ID

**Comment by xXNephowXx** [comment]
It doesn't work for me, I've tried the link, the private server Id, the game id and the link, the game Id and the private server Id and nothing works, please help ^^`

**Comment by xXNephowXx** [comment]
> It doesn't work for me, I've tried the link, the private server Id, the game id and the link, the game Id and the private server Id and nothing works, please help ^^`

Whenever I try it, nothing opens
