### ISSUE TITLE
Unable to use the Multi Roblox Function

### ISSUE THREAD

**Issue by AlterIsHere** [ic3w0lf22/Roblox-Account-Manager#361]
Whenever i join a game and try to join a alt to me while im In with Multi Roblox Function Activated, Roblox will just forcefully update my client and makes my main acc leave and the alt also crashes, im not sure whats the cause to this but its really annoying

**Comment by EgoBoi** [comment]
I'm having the exact same issue but don't know how to fix it.

**Comment by EgoBoi** [comment]
> Whenever i join a game and try to join a alt to me while im In with Multi Roblox Function Activated, Roblox will just forcefully update my client and makes my main acc leave and the alt also crashes, im not sure whats the cause to this but its really annoying

I fixed it just now by deleting all the roblox files on my pc (literally everything) then deleting account manager and then re-installing everything

**Comment by AlterIsHere** [comment]
> > Whenever i join a game and try to join a alt to me while im In with Multi Roblox Function Activated, Roblox will just forcefully update my client and makes my main acc leave and the alt also crashes, im not sure whats the cause to this but its really annoying
> 
> I fixed it just now by deleting all the roblox files on my pc (literally everything) then deleting account manager and then re-installing everything

there is a more simple fix where you go into where your roblox folder is located at and in the folder where the robloxclient is located at delete the one exe file called "Roblox Installer" That will fix the problem
