### ISSUE TITLE
New server list API

### ISSUE THREAD

**Issue by whentheis** [ic3w0lf22/Roblox-Account-Manager#37]
Roblox changed their server list endpoint and the server list no longer works on the account manager

**Comment by whentheis** [comment]
New endpoint for server list: https://games.roblox.com/v1/games/placeID/servers/Public?limit=100

**Comment by whentheis** [comment]
For reference you can use a fork of SearchBlox that implements the fix
https://github.com/lulu5239/SearchBlox/blob/patch-1/chrome/popup.js#L113 (fetching avatars)
https://github.com/lulu5239/SearchBlox/blob/patch-1/chrome/popup.js#L127 (fetching servers)

**Comment by whentheis** [comment]
Unfortunately I'm not good with C/C# so I can't edit it myself

**Comment by ic3w0lf22** [comment]
Fixed with 3.0 update
