### ISSUE TITLE
Wont join private server 

### ISSUE THREAD

**Issue by L1zar** [ic3w0lf22/Roblox-Account-Manager#4]
Kicks an issue where account is not allowed when joining private server.

![RobloxCantJoin](https://user-images.githubusercontent.com/68828580/88490705-4c254400-cf52-11ea-9eda-e36bd43f16c5.jpg)

If I try and join manually by launching a web browser, logging in as the account, and clicking join it will do so. When trying to join from the account manager it will not.

**Comment by ic3w0lf22** [comment]
The implementation for private servers is really bad, so you'll need to add `?privateServerLinkCode=` then the link to the server which you can find in the config.

**Comment by L1zar** [comment]
Ok so when you say I need to add it, what do I need to add it to?

**Comment by ic3w0lf22** [comment]
> Ok so when you say I need to add it, what do I need to add it to?

Add it to the JobId

**Comment by L1zar** [comment]
Thank you so much that worked and my life is so much better now!!!
