### ISSUE TITLE
DOES.... NOT..... WORK.... AT.... ALL

### ISSUE THREAD

**Issue by TNTPLAYZEXE318** [ic3w0lf22/Roblox-Account-Manager#404]
your shitty thing does not work AT ALL, every time i try to press "Add Account" it freezes, then it does nothing for like several seconds before a pop up appears and it says "You may have corrupted Chromium" .... FIX YOUR DAMN THING DUDE!!!

(sorry if i sound rude, im just tired of this shit)

**Comment by ic3w0lf22** [comment]
Stay mad
