### ISSUE TITLE
Closes all instances after joining on main through chrome

### ISSUE THREAD

**Issue by Kwquinch030** [ic3w0lf22/Roblox-Account-Manager#416]
I always open 3 alts through the Account Manager and after I join on my main through chrome but suddenly all 3 instances getting closed immidiently after I try to join on my main.

**Comment by Kwquinch030** [comment]
Always opening another window saying: Roblox is installing, Roblox is configuing and Roblox is starting.

**Comment by Kwquinch030** [comment]
I found the issue but I dont know how to fix it...
The game instances started by the account manager are based on another version of roblox then the chrome one...
![image](https://github.com/user-attachments/assets/8a4f8a3e-216d-49b9-8032-fd3f963e3fc7)

**Comment by yamaimimux** [comment]
Having the same problem right now , still looking out for possible solutions

**Comment by GitLord420** [comment]
I am having the same issue rn, i open my main account and when i open my alt my main automatically closes and when i launch any other account, it closes the previous instances i dont know what's happening but any help would be appreciated

**Comment by GitLord420** [comment]
I found a solution 
![Screenshot 2024-07-17 232114](https://github.com/user-attachments/assets/18a877d8-e8be-4d97-8389-3987cd29bced)
delete everything except the Account data and then reopen multi instance , enable multi instances again and you'll most probably have your fix

**Comment by ic3w0lf22** [comment]
the solution is to launch only from account manager
