### ISSUE TITLE
Executor not working

### ISSUE THREAD

**Issue by h101-nazi** [ic3w0lf22/Roblox-Account-Manager#42]
Hey i tried doing alot of stuff but here you go
![image](https://user-images.githubusercontent.com/58152056/168424519-53fbfa6a-57a6-49bb-9460-8f399383e412.png)
I'm sure you can fix this problem thanks

**Comment by ic3w0lf22** [comment]
This screenshot doesn't explain anything...

**Comment by h101-nazi** [comment]
idk i just restarded my pc and it worked thanks
