### ISSUE TITLE
Invalid Authentication Ticket

### ISSUE THREAD

**Issue by dilster4791** [ic3w0lf22/Roblox-Account-Manager#420]
![image](https://github.com/user-attachments/assets/ebf3b4f2-c3e7-492d-aefa-a32b3fb40fbd)
Re-adding accounts did not fix, re-installing software did not either.
Any solutions?

**Comment by L444SIN** [comment]
yo a solution I used for this issue was literally using the "open browser" feature instead of just clicking the join server so you have to manually join the game yourself from account managers roblox website

**Comment by mungislolkl** [comment]
> ![image_2024-07-17_172634130](https://private-user-images.githubusercontent.com/175893363/349688956-7cc65ab2-bf43-49f3-ad78-82688141ec8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNTIxMDYsIm5iZiI6MTcyMTI1MTgwNiwicGF0aCI6Ii8xNzU4OTMzNjMvMzQ5Njg4OTU2LTdjYzY1YWIyLWJmNDMtNDlmMy1hZDc4LTgyNjg4MTQxZWM4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QyMTMwMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGExNjYzMjVlYzI1MzRkY2RmMzQxYjRmYTI5Yjg3NzM5NzIyYzc0MWNhNjYzNDVkNDMxY2I2MjI0YzYwNDcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R3aiFO19OK05IWjDD_V9nSfdRRSl9ej7U2fO4dU31NY) yo a solution I used for this issue was literally using the "open browser" feature instead of just clicking the join server so you have to manually join the game yourself from account managers roblox website
> 
> @dilster4791

it only works for 3 accounts and then it closes th if you add another

**Comment by L444SIN** [comment]
> > ![image_2024-07-17_172634130](https://private-user-images.githubusercontent.com/175893363/349688956-7cc65ab2-bf43-49f3-ad78-82688141ec8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNTIxMDYsIm5iZiI6MTcyMTI1MTgwNiwicGF0aCI6Ii8xNzU4OTMzNjMvMzQ5Njg4OTU2LTdjYzY1YWIyLWJmNDMtNDlmMy1hZDc4LTgyNjg4MTQxZWM4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QyMTMwMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGExNjYzMjVlYzI1MzRkY2RmMzQxYjRmYTI5Yjg3NzM5NzIyYzc0MWNhNjYzNDVkNDMxY2I2MjI0YzYwNDcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R3aiFO19OK05IWjDD_V9nSfdRRSl9ej7U2fO4dU31NY) yo a solution I used for this issue was literally using the "open browser" feature instead of just clicking the join server so you have to manually join the game yourself from account managers roblox website
> > @dilster4791
> 
> it only works for 3 accounts and then it closes th if you add another

thats weird cause for me it works fine when I did it this way unfortunate then he'll probably drop a newer version soon hopefully it fixes this shit

**Comment by MohamedAlguhiem** [comment]
> ![image](https://private-user-images.githubusercontent.com/133361162/349590961-ebf3b4f2-c3e7-492d-aefa-a32b3fb40fbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNjE2ODcsIm5iZiI6MTcyMTI2MTM4NywicGF0aCI6Ii8xMzMzNjExNjIvMzQ5NTkwOTYxLWViZjNiNGYyLWMzZTctNDkyZC1hZWZhLWEzMmIzZmI0MGZiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQwMDA5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTEzMjdkMmQyNjQ3ZjNiMTBmMDAyMTNkNmMxYzQyNWJlMTUxNzE2NzYyOGZjNzdiODA5NWRkNTAyNmMxYTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K21ZmVP8eJQE-xK5aPyJyepSoaJw_3riZEmsRMPK_fA) Re-adding accounts did not fix, re-installing software did not either. Any solutions?

same issue here

**Comment by ic3w0lf22** [comment]
Fixed in 3.7.2
