### ISSUE TITLE
Antivirus and Virus Total says that the alt manager is a trojan(keylogger) and malware

### ISSUE THREAD

**Issue by ORB-Aerospace911** [ic3w0lf22/Roblox-Account-Manager#43]
![image](https://user-images.githubusercontent.com/79132854/169643405-ea860765-4635-4e2c-8190-e357e35df9eb.png)
![image](https://user-images.githubusercontent.com/79132854/169643413-1e3414e7-7725-4e5a-8c4c-972088abfc9d.png)
![image](https://user-images.githubusercontent.com/79132854/169643418-edfc024c-0aa3-499d-9ed4-63695aaedb9f.png)

**Comment by ic3w0lf22** [comment]
No idea what causes it, this is a common issue with open source software.
Not planning on attempting to fix it.

**Comment by bob448** [comment]
Whenever it says 3 or 2 it's most likely a false positive. If it's more then 10, then it's a virus.

**Comment by bloxain** [comment]
as far as a know it is a false

**Comment by Rolexboy88cool** [comment]
bro just look in the source for key loggers lol

**Comment by matej118111** [comment]
Its just false-positive, if you don't trust just compile the program yourself directly from source and you will be 100% sure that there's no virus

**Comment by Cod3rInDesp4ir** [comment]
Can somebody help me? I love this software but there's one thing I NEED for it to have (just to make my life EVEN MORE easier.

I need to be able to highlight all my alt account (4 in total) and I need to join 1 game ON DIFFERENT SERVERS. I don't want to join the same exact server.

**Comment by prljav** [comment]
@Cod3rInDesp4ir make a separate, dont type in outdated issues

**Comment by Catking473** [comment]
this is a false positive, just ignore it
