### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by Alex1242141** [ic3w0lf22/Roblox-Account-Manager#436]
![image](https://github.com/user-attachments/assets/2229aea8-6a6b-4933-9390-5913309812b1)

**Comment by MiniMamen1** [comment]
i was seeing what they said and the antivirus see the roblox account manager as a trojan because is an open source, the same thing on the hydra, but its safe

**Comment by Alex1242141** [comment]
yesterday this software didn't have a virus and now suddenly it does

**Comment by ic3w0lf22** [comment]
all new versions will be detected as malware, always been this way since the very first release
