### ISSUE TITLE
VirusTotal

### ISSUE THREAD

**Issue by MTRv4** [ic3w0lf22/Roblox-Account-Manager#440]
VirusTotal detected a trojan with 17 of 67 antiviruses on version 3.7.2. This is the first time I see that many on a "safe" app and I hope you will be able to repair this issue because I'm not launching something like that (sorry)
![obraz_2024-07-18_133921173](https://github.com/user-attachments/assets/b3ccefa8-ebc3-49f2-8ffc-b86e9a9d9a3b)

**Comment by ayaanmd100** [comment]
the owner is ratting us, dont install this malicious program

**Comment by habidin2** [comment]
@ayaanmd100 really?

**Comment by ic3w0lf22** [comment]
add an exclusion in your antivirus

**Comment by Linokuni** [comment]
This is a rat i looked at the code and it said a new update i scaned it with microsoft antivirus and it says it was a rat
