### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by MommaPNPAC** [ic3w0lf22/Roblox-Account-Manager#442]
I updated my son's Roblox account manager when the update was available 2 days ago without issue. This morning I tried to update it on my profile and the computer has identified it as a trojan virus and will not download. It looks like the source codes were posted 2 days ago and then yesterday the zip file was changed. Anyone else having any issues?

**Comment by QueenNyxess** [comment]
yes same issue auto updated and my computer said it was a trojan

**Comment by demimikaelson** [comment]
Same here, saw a post on X about it but many people are saying it's a false positive

**Comment by MommaPNPAC** [comment]
I find that hard to believe since the same computer, just different profile, downloaded it 2 days ago with no problem and now there has been a change to the zip file and now it's flagging it.

**Comment by Zectxr** [comment]
It's not trojan, it only got flag as a trojan because of the autoupdate

**Comment by h4rldev** [comment]
# IT IS A TROJAN, it's got a score of 22 on virus total, and the author has since blocked messaging rights on the official discord server
#
# DO NOT USE THIS TOOL ANY LONGER

**Comment by idontknowwhattonamemyself** [comment]
> # IT IS A TROJAN, it's got a score of 22 on virus total, and the author has since blocked messaging rights on the official discord server
> # DO NOT USE THIS TOOL ANY LONGER

maybe because of retards like you !!!!!

**Comment by derpzisonthehub** [comment]
its a false positive

**Comment by h4rldev** [comment]
> > # IT IS A TROJAN, it's got a score of 22 on virus total, and the author has since blocked messaging rights on the official discord server
> > # DO NOT USE THIS TOOL ANY LONGER
> 
> maybe because of retards like you !!!!!

The release wasnt automated, meaning it could've had malicious code included, otherwise I would've agreed. @idontknowwhattonamemyself @derpzisonthehub @MiniMamen1

**Comment by MommaPNPAC** [comment]
![Screenshot 2024-07-19 143706](https://github.com/user-attachments/assets/c55411a2-903e-49d0-9d10-65ac7cbfaf4f)

This makes me feel better from the developer.

**Comment by ic3w0lf22** [comment]
add an exclusion.
