### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by Mika1072m** [ic3w0lf22/Roblox-Account-Manager#445]
When I updated it. My PC deleted it because there is a virus can someone explain

**Comment by derpzisonthehub** [comment]
false positive

**Comment by mason464** [comment]
same idk how to fix it

**Comment by MiniMamen1** [comment]
> When I updated it. My PC deleted it because there is a virus can someone explain

so, an open source usually dont have an windows check, so usually the anti virus will say that its an virus, its only that

**Comment by MiniMamen1** [comment]
> same idk how to fix it

you need to look for anything on your antivirus that says 
"Quarantine", then you exclude from there, usually its only that

**Comment by ic3w0lf22** [comment]
add an exclusion.
