### ISSUE TITLE
Don't download!

### ISSUE THREAD

**Issue by Tombcaller** [ic3w0lf22/Roblox-Account-Manager#447]
They've put some dodgy update in place to steal account data, and locked older versions from being used.

**Comment by derpzisonthehub** [comment]
false positive dumbass

**Comment by MiniMamen1** [comment]
first, its an false positive, second if they did to put any type of virus or trojan, the github would delete this thing and thirdly they dont locked, you don't know how to search

**Comment by Mishierom** [comment]
> false positive dumbass

can anyone confirm this one ?

**Comment by ic3w0lf22** [comment]
old versions no longer work due to an api change roblox did
