### ISSUE TITLE
Program completely uninstalled itself?

### ISSUE THREAD

**Issue by Nightmane** [ic3w0lf22/Roblox-Account-Manager#448]
Given the weird issues with the "false positive" (?) trojan thing, I woke up today to find that RAM had completely removed itself from my taskbar and was also uninstalled besides the original folder files despite me never once touching them and despite there being no indication from any anti-virus of it being seen as one and removed by it. Did anyone else's do this?

**Comment by boylava28** [comment]
This happened to me also. Its likely windows anti virus doing its thing.

**Comment by ic3w0lf22** [comment]
Your antivirus probably deleted the program, add an exclusion.
