### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by CamOnGitHubdude** [ic3w0lf22/Roblox-Account-Manager#449]
Trojan on new update

**Comment by derpzisonthehub** [comment]
false positive

**Comment by Mishierom** [comment]
> false positive

can anyone confirm this one beside this account? it's just kinda sus

**Comment by ayaanmd100** [comment]
> > false positive
> 
> can anyone confirm this one beside this account? it's just kinda sus

Nah it's safe if you have doubts you can read the source code

**Comment by MiniMamen1** [comment]
> > false positive
> 
> can anyone confirm this one beside this account? it's just kinda sus

its safe

**Comment by ic3w0lf22** [comment]
add an exclusion.
