### ISSUE TITLE
Undocumented API methods

### ISSUE THREAD

**Issue by nh084817** [ic3w0lf22/Roblox-Account-Manager#45]
I was looking through the source code of `AccountManager.cs` and noticed that there were multiple methods that are yet to be documented at [the developer API](https://ic3w0lf22.gitbook.io/roblox-account-manager/).

Here's to name a few,
localhost:port/`GetCSRFToken`
localhost:port/`GetBlockedList`
and
localhost:port/`ImportCookie?Token=cookie`

You should update the documentation, as well as the `RAMAccount.lua` file to include the missing methods.

**Comment by ic3w0lf22** [comment]
Added all 3 functions to docs.
RAMAccount.lua Import function will be fixed soon
