### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by SmartA-F** [ic3w0lf22/Roblox-Account-Manager#461]
after a recent update alt manager now flags as a virus and im unsure why

**Comment by ic3w0lf22** [comment]
Every version is flagged as a virus for about a month, assuming windows defender sees that many people use the program and eventually whitelist it after manually analyzing the file

**Comment by xquinn** [comment]
You can speed up the process by uploading your zip here https://www.mcafee.com/en-us/consumer-support/dispute-detection-allowlisting.html
