### ISSUE TITLE
i cannot open auto update/roblox acount manager 

### ISSUE THREAD

**Issue by xxXiro** [ic3w0lf22/Roblox-Account-Manager#464]
![image](https://github.com/user-attachments/assets/82f61388-7c9d-489b-82df-cfa13ab60b8f)
when i want to open my account mananger i get this error

**Comment by Bones1101** [comment]
@xxXiro Have you tried running as admin?

**Comment by xxXiro** [comment]
@Bones1101 yes and is still the same thing

**Comment by Bones1101** [comment]
@xxXiro Send a photo of the details tab please

**Comment by xxXiro** [comment]
@Bones1101 
![image](https://github.com/user-attachments/assets/c43f76d6-94da-4c13-bc58-60be8793c936)

**Comment by ic3w0lf22** [comment]
Update manually from the releases page.
