### ISSUE TITLE
vigua.a detected in update(?)

### ISSUE THREAD

**Issue by Calebtheaa** [ic3w0lf22/Roblox-Account-Manager#470]
just updated roblox account manager, havent used it in a while, then i get a GameHack and Vigua.A warning in microsoft defender (windows 10)

is this normal? or did someone mess up the updater

**Comment by ArsenyAFK** [comment]
Viruses were thrown in there after the update and the old versions don't work now

**Comment by ic3w0lf22** [comment]
Every new version released has virus detections, add an exclusion.
