### ISSUE TITLE
I have an issue! I have an error that happen.

### ISSUE THREAD

**Issue by mimi1234568** [ic3w0lf22/Roblox-Account-Manager#471]
I have an issue with Roblox Account Manager that won't let me open it or work. For some reason, it won't auto update.
![Screenshot 2024-07-28 161541](https://github.com/user-attachments/assets/804df59c-a8bb-4cc2-92b2-81896b2b5625)

**Comment by ArsenyAFK** [comment]
Viruses were thrown in there after the update and the old versions don't work now

**Comment by ic3w0lf22** [comment]
Re-install manually from the [releases page](https://github.com/ic3w0lf22/Roblox-Account-Manager/releases/tag/3.7.2), or run as administrator, your antivirus may be deleting it, so add an exclusion as well.
