### ISSUE TITLE
Roblox Account Manager.

### ISSUE THREAD

**Issue by mimi1234568** [ic3w0lf22/Roblox-Account-Manager#472]
I get these errors whenever I try to "update" or "force update". And when I try to add multiple alts, it gives me another error.
![Screenshot 2024-07-28 161541](https://github.com/user-attachments/assets/388e9d84-f926-4c5c-aa70-c2c9056834dc)

**Comment by IbisPlayzYT** [comment]
Try redownloading the 3.6.1 version, then go to window's virus threat protection to make sure that it doesn't read as a virus, it's not a virus but for some reason it's mistaken as a Trojan-, after that update it. That error message only appears when it hasn't updated to the newest version. This is what I did, and it's been working for me so far! Hope it helps! There should also be youtube tutorial going over it somewhere, I watched that to guide me through it.

**Comment by mimi1234568** [comment]
After I download it, do I extract or run?
