### ISSUE TITLE
how to connect own executor

### ISSUE THREAD

**Issue by vhedhxw** [ic3w0lf22/Roblox-Account-Manager#477]
where do i get nexus
executor: wave
![how](https://github.com/user-attachments/assets/4c2adcfd-f401-41d3-a477-820c160cdf47)
![how2](https://github.com/user-attachments/assets/458e2cb7-c1e6-4bc0-ae2b-50f299575582)

**Comment by ic3w0lf22** [comment]
no idea, never used wave, never will, and this is not wave support.
