### ISSUE TITLE
Auto Roblox Keeps Sayig Error Message

### ISSUE THREAD

**Issue by Tooxen2** [ic3w0lf22/Roblox-Account-Manager#48]
I do not know if its the update. Everytime I keep trying to lauch an account, it states the following: "An error has occurred: 'Connection', trying agian..." Over and Over. I have tried to go to a later version of Auto Roblox and it forces me to install the update thats why im wondering if its the updates fault. If anyone has a fix I will be pleased. Also if you need any more info feel free to ask!

**Comment by ic3w0lf22** [comment]
Fixed in latest version

**Comment by ic3w0lf22** [comment]
holdon im fightin the last elden ring boss

**Comment by Tooxen2** [comment]
nice
![image](https://user-images.githubusercontent.com/106867041/171995221-fbfa51c9-a210-4f0f-bbd3-754d9e830ece.png)

**Comment by Tooxen2** [comment]
Hey if you cannot find a fix for this, How do I completly unistall then Reinstall?
