### ISSUE TITLE
ACCOUNT GOT HACKED

### ISSUE THREAD

**Issue by manhoyuan** [ic3w0lf22/Roblox-Account-Manager#481]
ALL OF MY ACC THAT DONT HAVE LOCK EMAIL GOT HACKED , ALL OF MY ANIME DEFENDER ITEM , UNIT , GEM ALL GONE , AND 1 OF MY ACC GOT LOG OUT AND description said V$XZZ WAS HERE

**Comment by ic3w0lf22** [comment]
Don't download malware and you won't have this issue, beware of scripts you execute as well if you are using badware.
