### ISSUE TITLE
This is probably a Virus

### ISSUE THREAD

**Issue by Galaxy0Gamer** [ic3w0lf22/Roblox-Account-Manager#482]
![image](https://github.com/user-attachments/assets/293b3381-26f1-45a4-a384-82b2d7efbb1a)

I have seen a lot of closed issues about this app being a virus and every one saying it is a false positive, but please look at the image, then tell me it is a false positive to my face, HOW CAN A FALSE POSITIVE BE DETECTED 22 TIMES ON DIFFERENT ANTIVIRUSES????

this image is from avast on my computer:
![image](https://github.com/user-attachments/assets/bc1c8f78-1e2d-4178-9c9e-ab0c50beed17)

**Comment by gh0stf1sh** [comment]
It's open sourced you could just check the code urself if your worried. Or just don't use it.

We really don't need the millionth "is this a virus/this is a virus" issue to add onto the pile.

**Comment by ic3w0lf22** [comment]
False positive, make an exclusion or simply do not use the program.
