### ISSUE TITLE
please fix this update

### ISSUE THREAD

**Issue by Raphael-source** [ic3w0lf22/Roblox-Account-Manager#484]
I've been using the Roblox account manager for about 2 months and haven't had any issues with it during this time However, in this new update, there are several virus warnings, and I simply can't install something that says trojan detected I hope they fix this in the next update because I don't think I'll be able to find a good alternative anytime soon

**Comment by ihearttriplebaka** [comment]
maybe just download process manager click on robloxplayer beta i think then remove singleinstant i think thats what its called

**Comment by ic3w0lf22** [comment]
Add an exclusion in your antivirus.
