### ISSUE TITLE
Account Manager Deletes itself

### ISSUE THREAD

**Issue by CheeseMan017** [ic3w0lf22/Roblox-Account-Manager#486]
Whenever i extract the zip folder to get the launcher it asks me to update. If i say yes it updates and then the launcher deletes itself once the update is completed while the rest of the files stay. When i say no it gives me an error although it lets me get into the launcher and add accounts after way to many captchas. The problem is that it doesn't let me join any game through the launcher and it says another error when i try, "error cant access account data" something along those lines. what can i do to fix this?!?!

**Comment by ic3w0lf22** [comment]
`error cant access account data` is not an account manager error. You need to add an exclusion for the latest update, download it manually from the releases page.
