### ISSUE TITLE
rblx acc manager being 2x scaling how to fix?

### ISSUE THREAD

**Issue by pj9388** [ic3w0lf22/Roblox-Account-Manager#488]
![im2age](https://github.com/user-attachments/assets/5036d2b9-bc1a-4892-b8cb-d8155c928691)

**Comment by ic3w0lf22** [comment]
Close the program, open `RAMSettings.ini` with notepad, and change the `Scale` option to 1

**Comment by pj9388** [comment]
I can't find the scale option

**Comment by pj9388** [comment]
never mind. It was windows scale, Thank you!
