### ISSUE TITLE
Connection Problem

### ISSUE THREAD

**Issue by Tooxen2** [ic3w0lf22/Roblox-Account-Manager#49]
I believe there is a problem with my program. Everytime I try to Auto Roblox, it changes the settings inside of my RAMSettings and messes with my connection. Is there any way I can fix thi
![171995221-fbfa51c9-a210-4f0f-bbd3-754d9e830ece](https://user-images.githubusercontent.com/106867041/172017498-cdc2421f-9175-436f-b5de-c724591a76ae.png)
s

**Comment by ic3w0lf22** [comment]
update to latest version
