### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by Sallz2** [ic3w0lf22/Roblox-Account-Manager#495]
why are all the versions flagged as a virus by windows and online scanners

**Comment by gh0stf1sh** [comment]
no offense but like... did you even read the FAQ on the front page first?

https://github.com/ic3w0lf22/Roblox-Account-Manager?tab=readme-ov-file#q-why-is-this-program-detected-as-a-virus

**Comment by Linokuni** [comment]
like i get this error
![Screenshot 2024-08-10 222242](https://github.com/user-attachments/assets/18bd7b4a-6ed3-4b53-b4c6-80c5f878dd5d)
it says like i cant download it cuz it has an virus or and unwanted software

**Comment by gh0stf1sh** [comment]
youll probably have to exclude it from whatever antivirus software you have in order for it to download, if its windows defender i think theres a video link on the front page lower on the FAQ too

**Comment by Sallz2** [comment]
[image: image.png]
[image: image.png]

**Comment by InCrIpTiOn** [comment]
Downloading from github gives
![image](https://github.com/user-attachments/assets/8d656414-859a-483b-b767-cd364f78889d)

**Comment by ReloadingMindustrythatcrash** [comment]
> Downloading from github gives ![image](https://private-user-images.githubusercontent.com/23437039/357887874-8d656414-859a-483b-b767-cd364f78889d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3Mzc3MTksIm5iZiI6MTcyMzczNzQxOSwicGF0aCI6Ii8yMzQzNzAzOS8zNTc4ODc4NzQtOGQ2NTY0MTQtODU5YS00ODNiLWI3NjctY2QzNjRmNzg4ODlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDE1NTY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllODZkMjI0OTkzYmRkYzRmYzNlM2Q3ZDE0NDU2MzkxNmMzYjZmZDdjZmZjNTI1ZjAyYjg2NmVlZmU0MWUwODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Za-nABdZyWlDpKXYUM_1zp44hALhBgB_kvl3k4jOk9U)

yea i think it contains some kind of trojan
if i'm guess right as long as u don't update the older version it should work fine
idk since last time i did that it doesn't let me in due to the "authorize ticket" thing
and it was fixed in the newest version
(yea it's possible for those situations happen if it's a opensource without good protection)

**Comment by ReloadingMindustrythatcrash** [comment]
from my experience where i've downloaded a opensource, it can happen

**Comment by NotSoHero** [comment]
> yea i think it contains some kind of trojan if i'm guess right as long as u don't update the older version it should work fine

does this mean i have to use an older version for it to be safe? if so which one.
