### ISSUE TITLE
Login menu wont load anything.

### ISSUE THREAD

**Issue by Noahbt787** [ic3w0lf22/Roblox-Account-Manager#51]
![image](https://user-images.githubusercontent.com/107649344/174156930-b0693d96-91a9-42b6-9bf3-88e16bec3c85.png)

**Comment by ic3w0lf22** [comment]
Download the latest .NET Framework
Install vcredist (You may need to install older versions as well, scroll down to find them) https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
