### ISSUE TITLE
Adding extensions to browser

### ISSUE THREAD

**Issue by vvirtues** [ic3w0lf22/Roblox-Account-Manager#510]
I know the guide says add to an extension folder, but should the crx file be places or the raw folder itself?

**Comment by vvirtues** [comment]
Nevermind, it requires the entire folder, like `load unpacked`.

Here's a URL for downloading whatever extension you want:
https://clients2.google.com/service/update2/crx?response=redirect&prodversion=124.0.6367.201&acceptformat=crx2,crx3&x=id%3D<PUT_ID_HERE>%26uc
Replace with ID from store, e.g. if link is `https://chromewebstore.google.com/detail/ropro-enhance-your-roblox/adbacgifemdbhdkfppmeilbgppmhaobf` then use `adbacgifemdbhdkfppmeilbgppmhaobf`

**Comment by vvirtues** [comment]
actually, the extensions seem to get removed and re-added, clearing all data. I'll turn this into a feature request for saving extension data and automatically loading multple extensions

**Comment by sudragonnabih0** [comment]
can you help me ?
i cant add 2captcha extension can you tell me how

**Comment by sudragonnabih0** [comment]
i get failed  to load extension:<My location> manifest file is missing or unreadable

**Comment by sudragonnabih0** [comment]
![image](https://github.com/user-attachments/assets/e7b14618-1416-4ad5-b689-f851dcccc6b5)

**Comment by vvirtues** [comment]
![image](https://github.com/user-attachments/assets/4533a1c7-ae98-4843-9c67-756900f2638a)
should look like this minus the crx file I have there

**Comment by vvirtues** [comment]
you need to get the crx, extract it and place the bare files

**Comment by sudragonnabih0** [comment]
can you tell me how ?
![image](https://github.com/user-attachments/assets/d1dc0e56-9547-4761-a220-2aaeac089a19)

**Comment by vvirtues** [comment]
> Nevermind, it requires the entire folder, like `load unpacked`.
> 
> Here's a URL for downloading whatever extension you want: `https://clients2.google.com/service/update2/crx?response=redirect&prodversion=124.0.6367.201&acceptformat=crx2,crx3&x=id%3D<PUT_ID_HERE>%26uc` Replace with ID from store, e.g. if link is `https://chromewebstore.google.com/detail/adbacgifemdbhdkfppmeilbgppmhaobf` then use `adbacgifemdbhdkfppmeilbgppmhaobf`

whats the extension's chrome link?
use this from my message above and replace the part of the link in that URL

**Comment by vvirtues** [comment]
oh wait 
download z-zip and open that file with it

**Comment by vvirtues** [comment]
winrar should work too if you already have it

**Comment by sudragonnabih0** [comment]
![image](https://github.com/user-attachments/assets/22f40347-9f6d-4cdc-b224-6cb06e1496e7)

**Comment by vvirtues** [comment]
google is your friend
https://youtu.be/ZanBSZqY_HA?si=HWfWsD2iJ5ibH0dP

**Comment by sudragonnabih0** [comment]
oh okay thanks is work
but can you tell me how to add captcha solver ( 2captcha ) in the tool

**Comment by vvirtues** [comment]
i dont know, i didnt make the program
