### ISSUE TITLE
Crashing on start

### ISSUE THREAD

**Issue by NICKISBAD** [ic3w0lf22/Roblox-Account-Manager#53]
When i start it on windows 7 it crashes upon startup
![githubproof](https://user-images.githubusercontent.com/107813557/174498748-5ae557ff-cfdb-4d25-a601-a3beba2b29ee.PNG)

**Comment by ic3w0lf22** [comment]
Download the latest .NET Framework
Install vcredist (You may need to install older versions as well, scroll down to find them) https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
