### ISSUE TITLE
Suggestion: Add a small delay on Nexus.lua

### ISSUE THREAD

**Issue by chavinlo** [ic3w0lf22/Roblox-Account-Manager#55]
I spent a few hours wondering why Nexus.lua didn't injected and it was because of it executing before the game loads, at least with synapse with custom launcher configuration.

I added this small piece of code and it worked:
```
if not game:IsLoaded() then
    game.Loaded:Wait()
    end

wait(15)
```

**Comment by ic3w0lf22** [comment]
never had this issue or had it reported before. i won't be adding a small delay considering nexus can be modified.
