### ISSUE TITLE
Can't load all the accounts at once, have to go each one and load it before you can load another one.

### ISSUE THREAD

**Issue by Rimon551** [ic3w0lf22/Roblox-Account-Manager#57]
I don't know if I'm the only one who is having this issue, but I can't load all my 20ish accounts at once. I need to load one, wait for it to go in to the game, and after it loaded I can go to the other one. It really is annoying to do it sometimes cause I lose track of what I did load and what I didn't.

**Comment by BaconnCalebb** [comment]
Same thing kinda happening to me, its just not working anymore its weird i cant even have 2 accounts at the same time

**Comment by ic3w0lf22** [comment]
try turning off async join
i can't fix this through account manager, it's probably roblox ratelimiting you (antibot shit, idk)
