### ISSUE TITLE
More like suggestion but yes, Linux support

### ISSUE THREAD

**Issue by matej118111** [ic3w0lf22/Roblox-Account-Manager#59]
Yes Roblox is not for linux but there are emulators like grapejuice could you atleast add grapejuice support with some basic features? I don't want to switch to Windows everytime i want to use multiple account or fast switch accounts, adding that feature would be cool, and also yes i tried running this program using Wine and Bottles, both didn't work its missing some dependencies to work i guess and i don't know which ones cause it doesn't say

Also even telling me which dependencies it requires would be cool

**Comment by abrahampo1** [comment]
> Yes Roblox is not for linux but there are emulators like grapejuice could you atleast add grapejuice support with some basic features? I don't want to switch to Windows everytime i want to use multiple account or fast switch accounts, adding that feature would be cool, and also yes i tried running this program using Wine and Bottles, both didn't work its missing some dependencies to work i guess and i don't know which ones cause it doesn't say
> 

I Made an alternative to RAM called ROAM https://ro-am.eu

Is made on NodeJs Electron and is fully compatible with linux (also open source) you can take a look in my git account

**Comment by matej118111** [comment]
> > Yes Roblox is not for linux but there are emulators like grapejuice could you atleast add grapejuice support with some basic features? I don't want to switch to Windows everytime i want to use multiple account or fast switch accounts, adding that feature would be cool, and also yes i tried running this program using Wine and Bottles, both didn't work its missing some dependencies to work i guess and i don't know which ones cause it doesn't say
> > 
> 
> I Made an alternative to RAM called ROAM https://ro-am.eu
> 
> Is made on NodeJs Electron and is fully compatible with linux (also open source) you can take a look in my git account

yes i will look at it later, thanks

**Comment by SwoopedGalaxySG** [comment]
> > Yes Roblox is not for linux but there are emulators like grapejuice could you atleast add grapejuice support with some basic features? I don't want to switch to Windows everytime i want to use multiple account or fast switch accounts, adding that feature would be cool, and also yes i tried running this program using Wine and Bottles, both didn't work its missing some dependencies to work i guess and i don't know which ones cause it doesn't say
> 
> I Made an alternative to RAM called ROAM https://ro-am.eu
> 
> Is made on NodeJs Electron and is fully compatible with linux (also open source) you can take a look in my git account

Is there a MacOS Version of it?

**Comment by abrahampo1** [comment]
> > > Yes Roblox is not for linux but there are emulators like grapejuice could you atleast add grapejuice support with some basic features? I don't want to switch to Windows everytime i want to use multiple account or fast switch accounts, adding that feature would be cool, and also yes i tried running this program using Wine and Bottles, both didn't work its missing some dependencies to work i guess and i don't know which ones cause it doesn't say
> 
> > 
> 
> > I Made an alternative to RAM called ROAM https://ro-am.eu
> 
> > 
> 
> > Is made on NodeJs Electron and is fully compatible with linux (also open source) you can take a look in my git account
> 
> 
> 
> Is there a MacOS Version of it?

Yep, i can compile a binary for MacOS, but i need to adapt The ROBLOX Client api module to work on mac ^^

**Comment by SwoopedGalaxySG** [comment]
> > > > > Yes Roblox is not for linux but there are emulators like grapejuice could you atleast add grapejuice support with some basic features? I don't want to switch to Windows everytime i want to use multiple account or fast switch accounts, adding that feature would be cool, and also yes i tried running this program using Wine and Bottles, both didn't work its missing some dependencies to work i guess and i don't know which ones cause it doesn't say
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > I Made an alternative to RAM called ROAM https://ro-am.eu
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Is made on NodeJs Electron and is fully compatible with linux (also open source) you can take a look in my git account
> > > 
> > > 
> > > Is there a MacOS Version of it?
> > 
> > 
> > Yep, i can compile a binary for MacOS, but i need to adapt The ROBLOX Client api module to work on mac ^^
> 
> YESS THANK YOU <3



> > > > Yes Roblox is not for linux but there are emulators like grapejuice could you atleast add grapejuice support with some basic features? I don't want to switch to Windows everytime i want to use multiple account or fast switch accounts, adding that feature would be cool, and also yes i tried running this program using Wine and Bottles, both didn't work its missing some dependencies to work i guess and i don't know which ones cause it doesn't say
> > 
> > 
> > > 
> > 
> > 
> > > I Made an alternative to RAM called ROAM https://ro-am.eu
> > 
> > 
> > > 
> > 
> > 
> > > Is made on NodeJs Electron and is fully compatible with linux (also open source) you can take a look in my git account
> > 
> > 
> > Is there a MacOS Version of it?
> 
> Yep, i can compile a binary for MacOS, but i need to adapt The ROBLOX Client api module to work on mac ^^

Please DM me when you've done updating for MacOS! Thank you so much!
Also please teach me how to use lol, contact me on Discord please: air#5400

**Comment by SwoopedGalaxySG** [comment]
> > > > Yes Roblox is not for linux but there are emulators like grapejuice could you atleast add grapejuice support with some basic features? I don't want to switch to Windows everytime i want to use multiple account or fast switch accounts, adding that feature would be cool, and also yes i tried running this program using Wine and Bottles, both didn't work its missing some dependencies to work i guess and i don't know which ones cause it doesn't say
> > 
> > 
> > > 
> > 
> > 
> > > I Made an alternative to RAM called ROAM https://ro-am.eu
> > 
> > 
> > > 
> > 
> > 
> > > Is made on NodeJs Electron and is fully compatible with linux (also open source) you can take a look in my git account
> > 
> > 
> > Is there a MacOS Version of it?
> 
> Yep, i can compile a binary for MacOS, but i need to adapt The ROBLOX Client api module to work on mac ^^

Also, does your RAM have same features as this RAM?

**Comment by abrahampo1** [comment]
> > > > > Yes Roblox is not for linux but there are emulators like grapejuice could you atleast add grapejuice support with some basic features? I don't want to switch to Windows everytime i want to use multiple account or fast switch accounts, adding that feature would be cool, and also yes i tried running this program using Wine and Bottles, both didn't work its missing some dependencies to work i guess and i don't know which ones cause it doesn't say
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > I Made an alternative to RAM called ROAM https://ro-am.eu
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Is made on NodeJs Electron and is fully compatible with linux (also open source) you can take a look in my git account
> 
> > > 
> 
> > > 
> 
> > > Is there a MacOS Version of it?
> 
> > 
> 
> > Yep, i can compile a binary for MacOS, but i need to adapt The ROBLOX Client api module to work on mac ^^
> 
> 
> 
> Also, does your RAM have same features as this RAM?

Yep it has, and have some more features (like aes256 crypto with personal password or followlinks)

You can checkout The webpage 

https://ro-am.eu

**Comment by ic3w0lf22** [comment]
closing cause email's being spammed, linux support may be possible in the future as well
