### ISSUE TITLE
"Follow" doesnt work. Error Code 522

### ISSUE THREAD

**Issue by ClickClack7531** [ic3w0lf22/Roblox-Account-Manager#64]
I think I found a glitch with the Follow feature.

I have never used this program before so I have no idea on how to use it, so what Im doing is purely based of assumptions.

I want to have my main account and my alt account join the same server. So what I did was I added my main account and my alt account by using the "Add Account" button. I was able to sign in successfully with both and I have them both in the left hand block. Ok, now, I want them to join the same server, so this is what I did. Under "Place ID" I added a numeral code that I grabbed from the link of the game Im going to play.
![{2CD2A5D0-1D66-42F7-87DD-65E057E4F04B}](https://user-images.githubusercontent.com/93358773/178154933-4b3d7b8d-79e9-4fbf-b7a7-46afec9b58bf.png)
And copied it into the box. Then, I single clicked my Main account in the box on the left and clicked the "Join Game" button, which successfully loads my Main into the game that I needed.
So, after than, 1. I typed my Main's username into the box next to "User name", 2. I singled clicked my alt account and then 3. clicked "Follow". A second Roblox player opens, but it doesnt load me into the game. It instead shows this error:
![image](https://user-images.githubusercontent.com/93358773/178155280-14c1c409-ad22-495d-8313-82b09feada05.png)
No, My Main did not leave the server nor timeout.

Does anyone know how to fix this? Am I doing something wrong?

**Comment by ic3w0lf22** [comment]
This isn't a bug, instead it means your main roblox profile's join privacy is not set correctly, or roblox bugged out and thinks your main account is offline even though it isn't. Also the process of following someone is mostly not done within account manager, the roblox launcher handles all that by using the parameters provided to the launcher from the account manager.

**Comment by ClickClack7531** [comment]
@ic3w0lf22 So, What I need to do is to set my settings to allow everyone to join my server?

**Comment by ClickClack7531** [comment]
> @ic3w0lf22 So, What I need to do is to set my settings to allow everyone to join my server?

For those who dont know what I did to fix this You have to go into your Roblox settings and allow anyone to join your game.

![{77C947E3-826B-4B5B-9DFD-5030C9C673B8}](https://user-images.githubusercontent.com/93358773/188272228-1e1e6cb9-d7e8-4ee7-a0f1-1a952e5073e7.png)

![{8A0D4FBF-AA98-498D-9C68-271EC23C1CE8}](https://user-images.githubusercontent.com/93358773/188272230-47a057bb-97e0-4b75-bc0b-a7c55431d60e.png)
