### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by SwoopedGalaxySG** [ic3w0lf22/Roblox-Account-Manager#65]

**Comment by SwoopedGalaxySG** [comment]
I'm a macos user and I really want this app to be able to use on my mac.

**Comment by ic3w0lf22** [comment]
[Launchbox](https://github.com/ccreaper/launchbox) supports macOS but I'm pretty sure it's not done or even working

**Comment by ic3w0lf22** [comment]
I don't have a mac but I may attempt in the future to add support for MacOS

**Comment by SwoopedGalaxySG** [comment]
> I don't have a mac but I may attempt in the future to add support for MacOS

Yes thank you! I really hope you can publish a MacOS version!

**Comment by orn8** [comment]
Still waiting for the MacOS version, it seems there aren't any alternatives. I've already tried running Roblox Account Manager through WINE on Mac, but that didn't work either.
