### ISSUE TITLE
Does this work with private server link?

### ISSUE THREAD

**Issue by monPE26715** [ic3w0lf22/Roblox-Account-Manager#8]
If it does, then please tell me how to.
If it doesn't then sad.

Thanks!

**Comment by ic3w0lf22** [comment]
It does, just paste in the private server link into the job id box, and make sure you have the correct place id as well.

**Comment by monPE26715** [comment]
Thanks!

**Comment by 14voetbal** [comment]
well when i do that and click on join server then i join btob and not the private server
