### ISSUE TITLE
Error code 523

### ISSUE THREAD

**Issue by Bonjourchik** [ic3w0lf22/Roblox-Account-Manager#81]
Hi! There was such a problem, after adding accounts and inserting the server code, the accounts are loaded, and then error code 523 appears. Is there a way to get around the error?
![6EYNsstst5](https://user-images.githubusercontent.com/75939560/181996968-c51400ab-1150-4536-83bd-dfe77dd91e0d.png)
![RBX_Alt_Manager_9Ac4X1qD7s](https://user-images.githubusercontent.com/75939560/181997002-4824d6a5-d003-4054-b209-c7ddefb56a5e.png)

**Comment by ic3w0lf22** [comment]
Can't reproduce, never happens to me, and nobody ever actually provides a working repro so don't expect a fix next update.
