### ISSUE TITLE
Account control doesn t detect that my account is playing

### ISSUE THREAD

**Issue by TreeV2** [ic3w0lf22/Roblox-Account-Manager#85]
title
using synapse
nexus.lua in autoexec
![image](https://user-images.githubusercontent.com/69603592/182447373-91f10685-36bd-4484-a006-c2cc3136a064.png)
![image](https://user-images.githubusercontent.com/69603592/182447588-6c4c8f92-c742-4394-aa8a-60676af57698.png)

**Comment by bloxain** [comment]
Make sure that the port localhost:5242 us open and your antivirus did not block it

**Comment by TreeV2** [comment]
> Make sure that the port localhost:5242 us open and your antivirus did not block it

how should i check? and before it worked but then it stopped

**Comment by ic3w0lf22** [comment]
is this issue still happening?
