### ISSUE TITLE
RBX Alt Manager.sln - unknown format

### ISSUE THREAD

**Issue by KiTBJUXXx** [ic3w0lf22/Roblox-Account-Manager#86]
![image](https://user-images.githubusercontent.com/110601247/182819369-4deb69ea-0ded-4307-a3fb-ce875dbe5816.png)

unknown format of file, so i cant open it, i checked up on YT, there people got .exe, how i fix it?

**Comment by ic3w0lf22** [comment]
maybe try clicking the button they press. not the first green button you see...

**Comment by KiTBJUXXx** [comment]
> 

i am doing in the same way as they
