### ISSUE TITLE
Roblox multiple instances not working

### ISSUE THREAD

**Issue by BoyBabaji** [ic3w0lf22/Roblox-Account-Manager#87]
i tried using it but it didn't work i dont know whats the actual problem but hopefully this get fixed

**Comment by bloxain** [comment]
wally — 04/01/2022
Q: Multi roblox does not work!
A: Close every process of the Roblox client. Open Task Manager, go to the Details tab, scroll down and look for processes named RobloxPlayerBeta.exe, right click and click End Task on all of them. 
After you are done with that, restart Roblox Account Manager.



Or use mutiroblox
