### ISSUE TITLE
How do you use Echo?

### ISSUE THREAD

**Issue by fheahdythdr** [ic3w0lf22/Roblox-Account-Manager#90]
In the Nexus docs, it says you can use Echo to send info to other clients, however I'm not entirely sure how to do so. Are you able to sync info with Nexus:Echo(...) between currently running clients or are you unable to?

**Comment by ic3w0lf22** [comment]
Nexus:Echo('hello wrodl!')

**Comment by bloxain** [comment]
I made the docs... Well you use Nexus:Echo('hi') on the host account and on as many accounts you want run



Nexus.MessageReceived:Connect(print)

Example Run on 1 account Nexus:Echo("kill all")

On other accounts Nexus.MessageReceived:Connect(function(Message)
	if Message == 'kill all' then
		game.players.localplayer.character.Humanoid.Health = 0
	end
end)

**Comment by fheahdythdr** [comment]
Like, example:
Syncing up a table between clients, which contains the order of 5 accounts (so for something like an alt control script)

**Comment by fheahdythdr** [comment]
Looking at it, probably.

**Comment by bloxain** [comment]
yes alt control the the whole reason i created it

**Comment by fheahdythdr** [comment]
no, more like syncing up different things like tables, general info
i want to use it to sync the order of accounts (my friend made a script that, when typing or sending something to it, it'll do something, but it uses the number in the account's name/display for the order)
