### ISSUE TITLE
Closes when alt joins

### ISSUE THREAD

**Issue by dcwsm** [ic3w0lf22/Roblox-Account-Manager#91]
when the first account joins it closes and then it opens the second account.

**Comment by bloxain** [comment]
Q: Multi roblox does not work!
A: Close every process of the Roblox client. Open Task Manager, go to the Details tab, scroll down and look for processes named RobloxPlayerBeta.exe, right click and click End Task on all of them. 
After you are done with that, restart Roblox Account Manager.
