### ISSUE TITLE
[Suggestion/Request] Save Job ID links for each account

### ISSUE THREAD

**Issue by bitfotico** [ic3w0lf22/Roblox-Account-Manager#92]
Heya strangers, I don't know the language to make it myself, though I use this software for farming with about a dozen accounts. On these accounts it's best to use a private server, which for the game I used is free, so I only use private servers with them. 

My current set-up is that I save each account's respective private server link in their description, and delete and copy/paste each time into the job ID for each account. The workload for me isn't significant, but very tedious, I was hoping it could be done for a new button or url link that saves across each account so I don't need to type in each of them every time =)

**Comment by ic3w0lf22** [comment]
already exists, click the save icon next to jobid
