### ISSUE TITLE
Roblox keeps launching

### ISSUE THREAD

**Issue by JustLevel** [ic3w0lf22/Roblox-Account-Manager#93]
My roblox keeps lauching even if a instance is already opens it keeps launching other ones..

**Comment by bloxain** [comment]
idk a lot of ppl say this still try
\
wally — 04/01/2022
Q: Multi roblox does not work!
A: Close every process of the Roblox client. Open Task Manager, go to the Details tab, scroll down and look for processes named RobloxPlayerBeta.exe, right click and click End Task on all of them. 
After you are done with that, restart Roblox Account Manager.

**Comment by ic3w0lf22** [comment]
turn off autolaunch
