### ISSUE TITLE
cant open multiple roblox accounts

### ISSUE THREAD

**Issue by KiTBJUXXx** [ic3w0lf22/Roblox-Account-Manager#97]
i cant get the account manager to open two accounts at once, the first one always closes when it tries to open the second one

**Comment by bloxain** [comment]
Q: Multi roblox does not work!
A: Close *every* process of the Roblox client. Open `Task Manager`, go to the `Details` tab, scroll down and look for processes named `RobloxPlayerBeta.exe`, right click and click `End Task` on **all** of them. 
After you are done with that, **restart** Roblox Account Manager.
