### ISSUE TITLE
[Suggestion] Headless ROBLOX clients

### ISSUE THREAD

**Issue by systemGene** [ic3w0lf22/Roblox-Account-Manager#98]
Don't know if this project is still being updated but who cares eh?
Adding an option for headless client for a user would be good to reduce RAM or CPU usage (that's what i've heard, don't know if it's real) plus it kinda looks funky with alot of clients open 

Hope to see a response :)

**Comment by ic3w0lf22** [comment]
no.

**Comment by systemGene** [comment]
> no.

oh
