### ISSUE TITLE
[Request] Save "Hide Usernames" Checkbox setting 

### ISSUE THREAD

**Issue by haootic** [ic3w0lf22/Roblox-Account-Manager#99]
I usually share my screen to people on discord a lot and I have a bunch of different alts which I don't want everyone knowing about but I still wanna be able to use the account manager, if I have the setting enabled and then close and reopen the program the setting does not save which is kinda annoying! please add !!!1.111!!111

**Comment by ic3w0lf22** [comment]
Added in next version
